import 'dart:math' as math;

import 'package:auto_size_text/auto_size_text.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:provider/provider.dart';

import '../../../../constants/theme_constants.dart';
import '../../../../providers/auth_provider.dart';
import '../../../../services/localization_service.dart';
import '../../models/inv_brand.dart';
import '../../models/inv_category.dart';
import '../../models/inv_product.dart';
import '../../providers/inventory_provider.dart';
import '../inventory_home.dart';
import '../widgets/inventory_widgets.dart';

class AddEditProductScreen extends StatefulWidget {
  const AddEditProductScreen({super.key, this.product});
  /// null => add mode, otherwise edit this existing product.
  final InvProduct? product;

  @override
  State<AddEditProductScreen> createState() => _AddEditProductScreenState();
}

class _AddEditProductScreenState extends State<AddEditProductScreen> {
  // Basic controllers
  final TextEditingController _name = TextEditingController();
  final TextEditingController _sku = TextEditingController();
  final TextEditingController _category = TextEditingController();
  final TextEditingController _cost = TextEditingController();
  final TextEditingController _price = TextEditingController();
  final TextEditingController _qty = TextEditingController();
  final TextEditingController _minStock = TextEditingController(text: '0');
  final TextEditingController _barcode = TextEditingController();
  final TextEditingController _createdBy = TextEditingController();
  final TextEditingController _description = TextEditingController();

  String _unit = 'crate';
  bool _active = true;
  bool _isRetail = false; // Default: turned off (Wholesale Mode)
  int? _categoryId;
  int? _brandId;
  bool _saving = false;

  // Size/variant list
  final List<_Variant> _variants = <_Variant>[
    _Variant(),
  ];

  bool _isSkuAutoGenerated = true;
  String _lastGeneratedSku = '';

  @override
  void initState() {
    super.initState();
    final InvProduct? p = widget.product;
    if (p == null) {
      _generateSku();
    } else {
      _isSkuAutoGenerated = false;
      _name.text = p.name;
      _sku.text = p.sku;
      _description.text = p.description ?? '';
      _category.text = p.categoryName ?? p.category;
      _cost.text = formatAmount(p.costPrice);
      _price.text = formatAmount(p.sellingPrice);
      _qty.text = p.quantity.toString();
      _minStock.text = p.minStock.toString();
      _barcode.text = p.barcode;
      _unit = p.unit;
      _active = p.status == 'active';
      _categoryId = p.categoryId;
      _brandId = p.brandId;
    }
    _name.addListener(_onNameChanged);
    _sku.addListener(_onSkuChanged);
    _cost.addListener(_rebuild);
    _price.addListener(_rebuild);
    _qty.addListener(_rebuild);

    WidgetsBinding.instance.addPostFrameCallback((_) {
      context.read<InventoryProvider>()
        ..fetchCategories()
        ..fetchBrands();
      final authUser = context.read<AuthProvider>().user;
      if (authUser != null && _createdBy.text.isEmpty) {
        _createdBy.text = authUser.name.isNotEmpty ? authUser.name : authUser.email;
      }
    });
  }

  void _onNameChanged() {
    if (_isSkuAutoGenerated && widget.product == null) {
      _generateSku(_name.text);
    }
  }

  void _onSkuChanged() {
    if (_sku.text != _lastGeneratedSku) {
      _isSkuAutoGenerated = false;
    }
  }

  void _generateSku([String? inputName]) {
    String prefix = 'SKU';
    final name = (inputName ?? _name.text).trim();
    if (name.isNotEmpty) {
      final parts = name.split(RegExp(r'\s+'));
      if (parts.length >= 2) {
        String p1 = parts[0].replaceAll(RegExp(r'[^a-zA-Z]'), '').toUpperCase();
        String p2 = parts[1].replaceAll(RegExp(r'[^a-zA-Z]'), '').toUpperCase();
        p1 = p1.length >= 3 ? p1.substring(0, 3) : (p1.isEmpty ? 'SKU' : p1.padRight(3, 'X'));
        p2 = p2.length >= 3 ? p2.substring(0, 3) : (p2.isEmpty ? '' : p2.padRight(3, 'X'));
        prefix = p2.isEmpty ? p1 : '$p1-$p2';
      } else {
        String p1 = parts[0].replaceAll(RegExp(r'[^a-zA-Z]'), '').toUpperCase();
        p1 = p1.length >= 3 ? p1.substring(0, 3) : (p1.isEmpty ? 'SKU' : p1.padRight(3, 'X'));
        prefix = p1;
      }
    }
    final int randomNum = 1000 + math.Random().nextInt(9000);
    _lastGeneratedSku = '$prefix-$randomNum';
    _isSkuAutoGenerated = true; // temporarily set true to bypass listener
    
    // update controller without triggering the focus change or caret reset if possible, 
    // but text update resets caret. To prevent caret jump when typing _name, 
    // we only update _sku value if it's not focused.
    _sku.value = TextEditingValue(
      text: _lastGeneratedSku,
      selection: TextSelection.collapsed(offset: _lastGeneratedSku.length),
    );
  }

  void _rebuild() {
    if (mounted) setState(() {});
  }

  @override
  void dispose() {
    _name.removeListener(_onNameChanged);
    _sku.removeListener(_onSkuChanged);
    _cost.removeListener(_rebuild);
    _price.removeListener(_rebuild);
    _qty.removeListener(_rebuild);
    _name.dispose();
    _sku.dispose();
    _category.dispose();
    _cost.dispose();
    _price.dispose();
    _qty.dispose();
    _minStock.dispose();
    _barcode.dispose();
    _createdBy.dispose();
    _description.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final loc = LocalizationService.instance;
    return Scaffold(
      backgroundColor: Colors.transparent,
      appBar: ThemeConstants.buildAppBar(
        widget.product == null
            ? loc.translate('add_product')
            : loc.translate('edit_product'),
        actions: [
          IconButton(
            icon: _saving
                ? SizedBox(
                    width: 18.w,
                    height: 18.w,
                    child: const CircularProgressIndicator(
                        strokeWidth: 2, color: Colors.white),
                  )
                : Icon(Icons.save, size: 20.sp),
            tooltip: loc.translate('save'),
            onPressed: _saving ? null : _onSave,
          ),
          IconButton(
            icon: Icon(Icons.delete_outline, size: 20.sp),
            tooltip: loc.translate('delete'),
            onPressed: _onDelete,
          ),
        ],
      ),
      bottomNavigationBar: _InventoryFooterForForm(),
      body: Stack(
        children: [
          const DecoratedBox(
            decoration: ThemeConstants.dashboardBackground,
            child: SizedBox.expand(),
          ),
          SafeArea(
            child: SingleChildScrollView(
              padding: EdgeInsets.all(8.w),
              child: Container(
                decoration: ThemeConstants.invCardDecoration,
                padding: EdgeInsets.all(8.w),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Business Mode Toggle (Wholesale vs Retail)
                    Container(
                      padding: EdgeInsets.symmetric(horizontal: 12.w, vertical: 8.h),
                      decoration: BoxDecoration(
                        color: _isRetail 
                            ? ThemeConstants.primaryOrange.withValues(alpha: 0.12)
                            : ThemeConstants.primaryCyan.withValues(alpha: 0.12),
                        borderRadius: BorderRadius.circular(14.r),
                        border: Border.all(
                          color: _isRetail 
                              ? ThemeConstants.primaryOrange.withValues(alpha: 0.35)
                              : ThemeConstants.primaryCyan.withValues(alpha: 0.35),
                        ),
                      ),
                      child: Row(
                        children: [
                          Icon(
                            _isRetail ? Icons.shopping_cart_outlined : Icons.inventory_2_outlined,
                            color: _isRetail ? ThemeConstants.primaryOrange : ThemeConstants.primaryCyan,
                            size: 22.sp,
                          ),
                          SizedBox(width: 10.w),
                          Expanded(
                            child: Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  _isRetail ? '🛒 Retail Mode (Rejareja)' : '🏬 Wholesale Mode (Jumla)',
                                  style: ThemeConstants.bodyStyle.copyWith(
                                    fontWeight: FontWeight.bold,
                                    color: _isRetail ? ThemeConstants.primaryOrange : ThemeConstants.primaryCyan,
                                  ),
                                ),
                                Text(
                                  _isRetail
                                      ? 'Rejareja: Inaonyesha vipimo vya moja moja na bei za Variants/Actual Price.'
                                      : 'Jumla (Default): Haionyeshi Variants wala Actual Price. Inatumia bei za Crate/Carton.',
                                  style: ThemeConstants.captionStyle.copyWith(fontSize: 10.sp),
                                ),
                              ],
                            ),
                          ),
                          Switch(
                            value: _isRetail,
                            activeThumbColor: ThemeConstants.primaryOrange,
                            onChanged: (v) {
                              setState(() {
                                _isRetail = v;
                                if (!_isRetail && (_unit == 'pcs' || _unit == 'bottle')) {
                                  _unit = 'crate';
                                } else if (_isRetail && _unit == 'crate') {
                                  _unit = 'pcs';
                                }
                              });
                            },
                          ),
                        ],
                      ),
                    ),
                    SizedBox(height: 12.h),

                    _twoCol(
                      left: _input(loc.translate('name'), _name,
                          hint: 'e.g. Coca-Cola 350ml'),
                      right: _input('SKU Code', _sku,
                          hint: 'e.g. COC-8429',
                          suffixIcon: IconButton(
                            icon: const Icon(Icons.refresh, color: ThemeConstants.primaryOrange, size: 20),
                            onPressed: _generateSku,
                            tooltip: 'Auto-generate SKU',
                            padding: EdgeInsets.zero,
                          )),
                    ),
                    if (_isRetail) ...[
                      SizedBox(height: 8.h),
                      _variantBlock(loc),
                    ],

                    SizedBox(height: 10.h),
                    _sectionTitle(loc.translate('product_description')),
                    _boxField(_description,
                        hint:
                            'e.g. Cold carbonated soft drink in 350ml glass bottles.'),



                    SizedBox(height: 12.h),
                    _sectionTitle('Inventory & Pricing'),
                    SizedBox(height: 6.h),
                    _twoCol(
                      left: _categoryPicker(loc),
                      right: _brandPicker(loc),
                    ),
                    SizedBox(height: 8.h),
                    Builder(builder: (ctx) {
                      final List<String> unitOptions = ['pcs', 'crate', 'carton', 'katoni', 'pack', 'box', 'tray', 'dozen', 'sack', 'kg', 'litre'];
                      if (!unitOptions.contains(_unit)) {
                        unitOptions.add(_unit);
                      }
                      return _dropdown('Unit', _unit, unitOptions, (v) {
                        setState(() => _unit = v!);
                      });
                    }),
                    SizedBox(height: 8.h),
                    Builder(builder: (context) {
                      final String unitLabel = _unit.trim().toUpperCase();
                      final double costVal = parseAmount(_cost.text);
                      final double priceVal = parseAmount(_price.text);
                      final double profitPerUnit = priceVal - costVal;

                      return Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _twoCol(
                            left: _input(
                                'Cost Price (kwa 1 $unitLabel)',
                                _cost,
                                keyboard: TextInputType.number,
                                inputFormatters: [ThousandsFormatter()],
                                hint: 'e.g. 20,000  ← Kununua 1 $_unit'),
                            right: _input(
                                'Selling Price (kwa 1 $unitLabel)',
                                _price,
                                keyboard: TextInputType.number,
                                inputFormatters: [ThousandsFormatter()],
                                hint: 'e.g. 25,000  ← Kuuza 1 $_unit'),
                          ),
                          Padding(
                            padding: EdgeInsets.symmetric(vertical: 4.h, horizontal: 2.w),
                            child: Text(
                              '💡 Faida kwa 1 $_unit = Selling Price − Cost Price  (Mfano: ${formatAmount(priceVal)} − ${formatAmount(costVal)} = TZS ${formatAmount(profitPerUnit)} kwa 1 $_unit)',
                              style: ThemeConstants.captionStyle.copyWith(
                                color: Colors.greenAccent.shade400,
                                fontSize: 11.sp,
                              ),
                            ),
                          ),
                          SizedBox(height: 8.h),
                          _twoCol(
                            left: _input('Quantity in Stock', _qty,
                                keyboard: TextInputType.number, hint: 'e.g. 100'),
                            right: _input('Stock Alert Threshold', _minStock,
                                keyboard: TextInputType.number, hint: 'e.g. 24'),
                          ),
                        ],
                      );
                    }),
                    if (_int(_qty.text) < _int(_minStock.text))
                      Padding(
                        padding: EdgeInsets.only(top: 6.h),
                        child: Container(
                          padding: EdgeInsets.symmetric(
                              horizontal: 8.w, vertical: 6.h),
                          decoration: BoxDecoration(
                              color: Colors.orange.shade700,
                              borderRadius: BorderRadius.circular(10.r)),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            children: [
                              Icon(Icons.warning_amber_rounded,
                                  color: Colors.white, size: 18.sp),
                              SizedBox(width: 6.w),
                              Text('Low Stock Alert',
                                  style: ThemeConstants.captionStyle.copyWith(
                                      color: Colors.white, fontSize: 11.sp)),
                            ],
                          ),
                        ),
                      ),

                    SizedBox(height: 8.h),
                    _twoCol(
                      left: _input('Barcode (optional)', _barcode,
                          hint: 'e.g. 600123456789'),
                      right: _switchRow('Status', _active,
                          (v) => setState(() => _active = v)),
                    ),
                    SizedBox(height: 8.h),
                    _twoCol(
                      left: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          _sectionTitle('Created By'),
                          TextField(
                            controller: _createdBy,
                            readOnly: true,
                            decoration: _decoration('Created By').copyWith(
                              prefixIcon: const Icon(Icons.person_outline,
                                  color: Colors.white38),
                              filled: true,
                              fillColor: Colors.white.withOpacity(0.05),
                            ),
                            style: ThemeConstants.bodyStyle
                                .copyWith(color: Colors.white54),
                          ),
                        ],
                      ),
                      right: const SizedBox.shrink(),
                    ),
                  ],
                ),
              ),
            ),
          )
        ],
      ),
    );
  }

  // UI building blocks
  Widget _variantBlock(LocalizationService loc) {
    // Each variant represents a pack/size with its own specific price
    Widget headerLabels() => Padding(
          padding: EdgeInsets.only(bottom: 4.h, left: 4.w, right: 4.w),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text(
                'Sizes / Variants  (Mfano: Crate ya 24, Carton ya 12, Bottle moja)',
                style: ThemeConstants.captionStyle.copyWith(color: Colors.white70, fontSize: 11.sp),
              ),
              SizedBox(height: 4.h),
              Row(
                children: [
                  SizedBox(
                      width: 80.w,
                      child: Text('Size/Pack', style: ThemeConstants.captionStyle)),
                  SizedBox(width: 6.w),
                  Expanded(
                      child: Text('Idadi (Qty)', style: ThemeConstants.captionStyle)),
                  SizedBox(width: 6.w),
                  Expanded(
                      child: Text('Bei Maalum\n(Actual Price)', style: ThemeConstants.captionStyle, maxLines: 2)),
                  SizedBox(width: 6.w),
                  Expanded(
                      child: Text('Bei ya Punguzo\n(Discounted)', style: ThemeConstants.captionStyle, maxLines: 2)),
                ],
              ),
            ],
          ),
        );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        headerLabels(),
        for (int i = 0; i < _variants.length; i++) ...[
          Row(
            children: [
              SizedBox(width: 80.w, child: _chip('Pack ${i + 1}')),
              SizedBox(width: 6.w),
              Expanded(child: _smallInput('e.g. 24 btl', _variants[i].qty)),
              SizedBox(width: 6.w),
              Expanded(child: _smallInput('e.g. 18,000', _variants[i].price, inputFormatters: [ThousandsFormatter()])),
              SizedBox(width: 6.w),
              Expanded(child: _smallInput('e.g. 16,000', _variants[i].discount, inputFormatters: [ThousandsFormatter()])),
              SizedBox(width: 6.w),
              if (_variants.length > 1)
                _dangerChip('Del', () {
                  setState(() => _variants.removeAt(i));
                }),
            ],
          ),
          SizedBox(height: 8.h),
          Row(
            children: [
              Checkbox(
                  value: true,
                  onChanged: (_) {},
                  activeColor: ThemeConstants.invAccent),
              _neutralChip('+ Ongeza Size/Pack', () {
                setState(() => _variants.add(_Variant()));
              }),
            ],
          ),
          SizedBox(height: 8.h),
        ],
      ],
    );
  }



  Widget _sectionTitle(String text) => Padding(
        padding: EdgeInsets.symmetric(vertical: 4.h),
        child: AutoSizeText(
          text,
          style: ThemeConstants.headingStyle.copyWith(fontSize: 14.sp),
          maxLines: 1,
          minFontSize: 11,
        ),
      );

  Widget _twoCol({required Widget left, required Widget right}) => Row(
        children: [
          Expanded(child: left),
          SizedBox(width: 6.w),
          Expanded(child: right),
        ],
      );

  Widget _boxField(TextEditingController c, {String? hint}) => TextField(
        controller: c,
        maxLines: 2,
        decoration: _decoration(hint ?? ''),
        style: ThemeConstants.bodyStyle,
      );

  Widget _input(String label, TextEditingController c,
          {String? hint, TextInputType? keyboard, Widget? suffixIcon, List<TextInputFormatter>? inputFormatters}) =>
      Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionTitle(label),
          TextField(
            controller: c,
            keyboardType: keyboard,
            inputFormatters: inputFormatters,
            decoration: suffixIcon != null 
                ? _decoration(hint ?? label).copyWith(suffixIcon: suffixIcon)
                : _decoration(hint ?? label),
            style: ThemeConstants.bodyStyle,
          ),
        ],
      );

  Widget _smallInput(String hint, TextEditingController c, {List<TextInputFormatter>? inputFormatters}) => SizedBox(
        height: 36.h,
        child: TextField(
          controller: c,
          inputFormatters: inputFormatters,
          decoration: _decoration(hint),
          style: ThemeConstants.bodyStyle,
        ),
      );

  InputDecoration _decoration(String hint) =>
      ThemeConstants.invInputDecoration(hint);

  Widget _dropdown(String label, String value, List<String> items,
          ValueChanged<String?> onChanged) =>
      Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          _sectionTitle(label),
          Container(
            padding: EdgeInsets.symmetric(horizontal: 10.w),
            decoration: BoxDecoration(
              color: ThemeConstants.invFill,
              borderRadius: BorderRadius.circular(14.r),
              border: Border.all(color: ThemeConstants.invBorder),
            ),
            child: DropdownButton<String>(
              value: value,
              isExpanded: true,
              dropdownColor: ThemeConstants.primaryBlue,
              underline: const SizedBox.shrink(),
              style: ThemeConstants.bodyStyle,
              items: items
                  .map(
                      (e) => DropdownMenuItem<String>(value: e, child: Text(e)))
                  .toList(),
              onChanged: onChanged,
            ),
          ),
        ],
      );

  Widget _switchRow(String label, bool val, ValueChanged<bool> onChanged) =>
      Container(
        padding: EdgeInsets.symmetric(horizontal: 10.w, vertical: 12.h),
        decoration: BoxDecoration(
          color: ThemeConstants.invFill,
          borderRadius: BorderRadius.circular(14.r),
          border: Border.all(color: ThemeConstants.invBorder),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            Text(label, style: ThemeConstants.bodyStyle),
            Switch(value: val, onChanged: onChanged),
          ],
        ),
      );

  Widget _chip(String text) => Container(
        padding: EdgeInsets.symmetric(horizontal: 8.w, vertical: 6.h),
        decoration: BoxDecoration(
          color: ThemeConstants.invNeutralChip,
          borderRadius: BorderRadius.circular(16.r),
          border: Border.all(color: ThemeConstants.invBorder),
        ),
        child: AutoSizeText(text,
            style: ThemeConstants.captionStyle, maxLines: 1, minFontSize: 10),
      );


  // Pill chip builder to guarantee identical height, radius, padding, and icon/text layout
  Widget _pillChip({
    required IconData icon,
    required String text,
    required Color bg,
    Color fg = Colors.white,
    VoidCallback? onTap,
  }) =>
      InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(18.r),
        child: Container(
          height: 36.h,
          padding: EdgeInsets.symmetric(horizontal: 14.w),
          decoration: BoxDecoration(
              color: bg, borderRadius: BorderRadius.circular(18.r)),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: [
              Icon(icon, color: fg.withValues(alpha: 0.9), size: 18.sp),
              SizedBox(width: 8.w),
              AutoSizeText(
                text,
                style: TextStyle(
                    color: fg, fontWeight: FontWeight.w600, fontSize: 13.sp),
                maxLines: 1,
                minFontSize: 10,
              ),
            ],
          ),
        ),
      );

  Widget _neutralChip(String text, VoidCallback onTap) => _pillChip(
        icon: Icons.edit_outlined,
        text: text,
        bg: const Color(0xFF1E3A46),
        onTap: onTap,
      );

  Widget _dangerChip(String text, VoidCallback onTap) => _pillChip(
        icon: Icons.delete_outline,
        text: text,
        bg: ThemeConstants.errorRed,
        onTap: onTap,
      );

  // Helpers
  int _int(String? s) => int.tryParse(s ?? '') ?? 0;

  Widget _categoryPicker(LocalizationService loc) {
    final InventoryProvider inv = context.watch<InventoryProvider>();
    final bool validCategory = _categoryId == null ||
        _categoryId == -1 ||
        inv.categories.any((InvCategory c) => c.id == _categoryId);
    final int? selectedValue = validCategory ? _categoryId : null;

    return DropdownButtonFormField<int?>(
      key: ValueKey<String>('cat_$selectedValue'),
      initialValue: selectedValue,
      isExpanded: true,
      dropdownColor: ThemeConstants.primaryBlue,
      style: ThemeConstants.bodyStyle,
      decoration: _decoration(loc.translate('category')),
      items: <DropdownMenuItem<int?>>[
        DropdownMenuItem<int?>(
          child: Text(loc.translate('no_category'),
              style: ThemeConstants.bodyStyle),
        ),
        ...inv.categories.map(
          (InvCategory c) => DropdownMenuItem<int?>(
            value: c.id,
            child: Text(c.name,
                overflow: TextOverflow.ellipsis,
                style: ThemeConstants.bodyStyle),
          ),
        ),
        DropdownMenuItem<int?>(
          value: -1,
          child: Text('+ ${loc.translate('add_category')}',
              style: const TextStyle(color: ThemeConstants.primaryOrange)),
        ),
      ],
      onChanged: (int? v) {
        if (v == -1) {
          Future.microtask(() => _createCategoryDialog(loc));
          return;
        }
        setState(() {
          _categoryId = v;
          final match = inv.categories.where((InvCategory c) => c.id == v);
          _category.text = match.isEmpty ? '' : match.first.name;
        });
      },
    );
  }

  Widget _brandPicker(LocalizationService loc) {
    final InventoryProvider inv = context.watch<InventoryProvider>();
    final bool validBrand = _brandId == null ||
        _brandId == -1 ||
        inv.brands.any((InvBrand b) => b.id == _brandId);
    final int? selectedValue = validBrand ? _brandId : null;

    return DropdownButtonFormField<int?>(
      key: ValueKey<String>('brand_$selectedValue'),
      initialValue: selectedValue,
      isExpanded: true,
      dropdownColor: ThemeConstants.primaryBlue,
      style: ThemeConstants.bodyStyle,
      decoration: _decoration(loc.translate('brand')),
      items: <DropdownMenuItem<int?>>[
        DropdownMenuItem<int?>(
          child:
              Text(loc.translate('no_brand'), style: ThemeConstants.bodyStyle),
        ),
        ...inv.brands.map(
          (InvBrand b) => DropdownMenuItem<int?>(
            value: b.id,
            child: Text(b.name,
                overflow: TextOverflow.ellipsis,
                style: ThemeConstants.bodyStyle),
          ),
        ),
        DropdownMenuItem<int?>(
          value: -1,
          child: Text('+ ${loc.translate('add_brand')}',
              style: const TextStyle(color: ThemeConstants.primaryOrange)),
        ),
      ],
      onChanged: (int? v) {
        if (v == -1) {
          Future.microtask(() => _createBrandDialog(loc));
          return;
        }
        setState(() => _brandId = v);
      },
    );
  }

  Future<void> _createCategoryDialog(LocalizationService loc) async {
    // No TextEditingController here on purpose: disposing one right after
    // the dialog's exit *transition* (which spans several frames after
    // showDialog resolves, not just the next one) raced the still-mounted
    // TextField reading it - "used after being disposed", then cascading
    // Overlay/GlobalKey errors. Plain onChanged has nothing to dispose.
    String draft = '';
    final String? name = await showDialog<String>(
      context: context,
      builder: (BuildContext ctx) => AlertDialog(
        backgroundColor: ThemeConstants.primaryBlue,
        shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
        title: Text(loc.translate('add_category'),
            style: ThemeConstants.headingStyle),
        content: TextField(
          autofocus: true,
          style: ThemeConstants.bodyStyle,
          decoration: _decoration(loc.translate('new_category_name')),
          onChanged: (String v) => draft = v,
          onSubmitted: (String v) => Navigator.pop(ctx, v.trim()),
        ),
        actions: <Widget>[
          TextButton(
              onPressed: () => Navigator.pop(ctx),
              child: Text(loc.translate('cancel'))),
          TextButton(
            onPressed: () => Navigator.pop(ctx, draft.trim()),
            child: Text(loc.translate('save')),
          ),
        ],
      ),
    );
    if (name == null || name.isEmpty || !mounted) return;

    final int? id =
        await context.read<InventoryProvider>().createCategory(name: name);
    if (id != null && mounted) {
      setState(() {
        _categoryId = id;
        _category.text = name;
      });
    }
  }

  Future<void> _createBrandDialog(LocalizationService loc) async {
    // See _createCategoryDialog for why this deliberately has no
    // TextEditingController.
    String draft = '';
    final String? name = await showDialog<String>(
      context: context,
      builder: (BuildContext ctx) => AlertDialog(
        backgroundColor: ThemeConstants.primaryBlue,
        shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
        title: Text(loc.translate('add_brand'),
            style: ThemeConstants.headingStyle),
        content: TextField(
          autofocus: true,
          style: ThemeConstants.bodyStyle,
          decoration: _decoration(loc.translate('new_brand_name')),
          onChanged: (String v) => draft = v,
          onSubmitted: (String v) => Navigator.pop(ctx, v.trim()),
        ),
        actions: <Widget>[
          TextButton(
              onPressed: () => Navigator.pop(ctx),
              child: Text(loc.translate('cancel'))),
          TextButton(
            onPressed: () => Navigator.pop(ctx, draft.trim()),
            child: Text(loc.translate('save')),
          ),
        ],
      ),
    );
    if (name == null || name.isEmpty || !mounted) return;

    final int? id =
        await context.read<InventoryProvider>().createBrand(name: name);
    if (id != null && mounted) {
      setState(() => _brandId = id);
    }
  }

  Future<void> _onSave() async {
    final LocalizationService loc = LocalizationService.instance;

    if (_name.text.trim().isEmpty || _sku.text.trim().isEmpty) {
      ThemeConstants.showWarningSnackBar(
          context, loc.translate('field_required'));
      return;
    }
    setState(() => _saving = true);
    final InventoryProvider inv = context.read<InventoryProvider>();
    final String? description =
        _description.text.trim().isEmpty ? null : _description.text.trim();
    final String? category =
        _category.text.trim().isEmpty ? null : _category.text.trim();
    final String? barcode =
        _barcode.text.trim().isEmpty ? null : _barcode.text.trim();
    final bool ok = widget.product != null
        ? await inv.updateProduct(
            id: widget.product!.id,
            name: _name.text.trim(),
            description: description,
            costPrice: parseAmount(_cost.text),
            sellingPrice: parseAmount(_price.text),
            quantity: _int(_qty.text),
            minStock: _int(_minStock.text),
            category: category,
            categoryId: _categoryId,
            brandId: _brandId,
            unit: _unit,
            status: _active ? 'active' : 'inactive',
            barcode: barcode,
          )
        : await inv.createProduct(
            name: _name.text.trim(),
            description: description,
            sku: _sku.text.trim(),
            costPrice: parseAmount(_cost.text),
            sellingPrice: parseAmount(_price.text),
            quantity: _int(_qty.text),
            minStock: _int(_minStock.text),
            category: category,
            categoryId: _categoryId,
            brandId: _brandId,
            unit: _unit,
            status: _active ? 'active' : 'inactive',
            barcode: barcode,
            priceTier: _isRetail ? 'retail' : 'wholesale',
          );

    if (!mounted) return;
    setState(() => _saving = false);
    if (ok) {
      ThemeConstants.showSuccessSnackBar(context, loc.translate('saved'));
      Navigator.pop(context);
    } else {
      ThemeConstants.showErrorSnackBar(
          context, loc.translate('operation_failed'));
    }
  }

  Future<void> _onDelete() async {
    final LocalizationService loc = LocalizationService.instance;
    final InvProduct? p = widget.product;
    if (p == null) {
      // Nothing to delete yet in add mode.
      return;
    }

    final bool? confirmed = await showDialog<bool>(
      context: context,
      builder: (BuildContext ctx) => AlertDialog(
        backgroundColor: ThemeConstants.primaryBlue,
        shape:
            RoundedRectangleBorder(borderRadius: BorderRadius.circular(16.r)),
        title: Text(loc.translate('delete'), style: ThemeConstants.headingStyle),
        content: Text(p.name, style: ThemeConstants.bodyStyle),
        actions: <Widget>[
          TextButton(
            onPressed: () => Navigator.pop(ctx, false),
            child: Text(loc.translate('cancel')),
          ),
          TextButton(
            onPressed: () => Navigator.pop(ctx, true),
            child: Text(loc.translate('delete')),
          ),
        ],
      ),
    );
    if (confirmed != true || !mounted) return;

    setState(() => _saving = true);
    final bool ok = await context.read<InventoryProvider>().deleteProduct(p.id);
    if (!mounted) return;
    setState(() => _saving = false);
    if (ok) {
      ThemeConstants.showSuccessSnackBar(context, loc.translate('deleted'));
      Navigator.pop(context);
    } else {
      ThemeConstants.showErrorSnackBar(
          context, loc.translate('operation_failed'));
    }
  }
}

class _InventoryFooterForForm extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ColoredBox(
      color: ThemeConstants.footerBarColor,
      child: SafeArea(
        top: false,
        child: ClipRRect(
          borderRadius: BorderRadius.circular(28.r),
          child: Container(
            width: double.infinity,
            margin: EdgeInsets.symmetric(vertical: 8.h),
            padding: EdgeInsets.symmetric(horizontal: 18.w, vertical: 10.h),
            decoration: BoxDecoration(
              color: ThemeConstants.footerBarColor,
              borderRadius: BorderRadius.circular(28.r),
              boxShadow: [
                BoxShadow(
                    color: Colors.black.withValues(alpha: 0.15),
                    blurRadius: 8,
                    offset: const Offset(0, 2)),
              ],
            ),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                _footerIcon(context, Icons.calendar_today_outlined,
                    () => _goto(context, 0)),
                Stack(children: [
                  _footerIcon(
                      context, Icons.person_outline, () => _goto(context, 1)),
                  Positioned(
                    right: 2,
                    top: 0,
                    child: Container(
                        width: 8.w,
                        height: 8.w,
                        decoration: const BoxDecoration(
                            color: Colors.amber, shape: BoxShape.circle)),
                  ),
                ]),
                _footerIcon(context, Icons.menu, () => _openMenu(context)),
                _footerIcon(
                    context, Icons.pets_outlined, () => _goto(context, 2)),
                _footerIcon(context, Icons.settings_outlined,
                    () => Navigator.pushNamed(context, '/settings')),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _footerIcon(BuildContext context, IconData icon, VoidCallback onTap) =>
      InkResponse(
        onTap: onTap,
        radius: 28.r,
        child: Container(
          width: 46.w,
          height: 46.w,
          decoration: BoxDecoration(
              color: ThemeConstants.primaryBlue.withValues(alpha: 0.22),
              shape: BoxShape.circle),
          child: Icon(icon, color: Colors.white, size: 22.sp),
        ),
      );

  void _goto(BuildContext context, int index) {
    Navigator.pushReplacement(
      context,
      MaterialPageRoute(builder: (_) => InventoryHome(initialIndex: index)),
    );
  }

  Future<void> _openMenu(BuildContext context) async {
    final loc = LocalizationService.instance;
    await showDialog<void>(
      context: context,
      builder: (ctx) => Dialog(
        backgroundColor: Colors.transparent,
        insetPadding: EdgeInsets.symmetric(horizontal: 16.w, vertical: 24.h),
        child: Container(
          decoration: BoxDecoration(
            color: ThemeConstants.primaryBlue.withValues(alpha: 0.95),
            borderRadius: BorderRadius.circular(20.r),
            border: Border.all(color: Colors.white24),
          ),
          padding: EdgeInsets.all(12.w),
          child: GridView.count(
            crossAxisCount: 3,
            mainAxisSpacing: 12.w,
            crossAxisSpacing: 12.w,
            shrinkWrap: true,
            children: [
              _gridItem(context, Icons.dashboard, loc.translate('dashboard'),
                  () => _goto(context, 0)),
              _gridItem(context, Icons.inventory_2_outlined,
                  loc.translate('products'), () => _goto(context, 1)),
              _gridItem(context, Icons.track_changes_outlined,
                  loc.translate('stock_levels'), () => _goto(context, 2)),
              _gridItem(
                  context,
                  Icons.sync_alt_outlined,
                  loc.translate('stock_in_out_transfer'),
                  () => _goto(context, 3)),
              _gridItem(context, Icons.point_of_sale_outlined,
                  loc.translate('sales'), () => _goto(context, 4)),
              _gridItem(context, Icons.category_outlined, 'Categories',
                  () => _goto(context, 5)),
            ],
          ),
        ),
      ),
    );
  }

  Widget _gridItem(BuildContext context, IconData icon, String label,
          VoidCallback onTap) =>
      InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(16.r),
        child: Container(
          decoration: BoxDecoration(
              color: ThemeConstants.invNeutralChip,
              borderRadius: BorderRadius.circular(16.r)),
          padding: EdgeInsets.all(10.w),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: [
              Icon(icon, color: Colors.white, size: 24.sp),
              SizedBox(height: 8.h),
              AutoSizeText(label,
                  style: ThemeConstants.bodyStyle,
                  maxLines: 2,
                  minFontSize: 10,
                  textAlign: TextAlign.center),
            ],
          ),
        ),
      );
}

class _Variant {
  _Variant();
  final TextEditingController qty = TextEditingController();
  final TextEditingController price = TextEditingController();
  final TextEditingController discount = TextEditingController();
}
