import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

// ignore_for_file: prefer_constructors_over_static_methods
class LocalizationService extends ChangeNotifier {
  LocalizationService._internal();
  static const String _languageKey = 'selected_language';

  Locale _currentLocale = const Locale('sw', 'TZ'); // Default to Swahili

  Locale get currentLocale => _currentLocale;
  String get currentLanguage => _currentLocale.languageCode;
  bool get isSwahili => _currentLocale.languageCode == 'sw';
  bool get isEnglish => _currentLocale.languageCode == 'en';

  static LocalizationService? _instance;

  static LocalizationService get instance {
    _instance ??= LocalizationService._internal();
    return _instance!;
  }

  Future<void> initialize() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    final String? savedLanguage = prefs.getString(_languageKey);

    if (savedLanguage != null) {
      _currentLocale = _getLocaleFromLanguageCode(savedLanguage);
    }

    notifyListeners();
  }

  Future<void> changeLanguage(String languageCode) async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);

    _currentLocale = _getLocaleFromLanguageCode(languageCode);
    notifyListeners();
  }

  Locale _getLocaleFromLanguageCode(String languageCode) {
    switch (languageCode) {
      case 'en':
        return const Locale('en', 'US');
      case 'sw':
      default:
        return const Locale('sw', 'TZ');
    }
  }

  String translate(String key) {
    return AppLocalizations.instance.translate(key);
  }
}

class AppLocalizations {
  AppLocalizations._internal();
  static AppLocalizations? _instance;
  static AppLocalizations get instance {
    _instance ??= AppLocalizations._internal();
    return _instance!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'camera_permission_denied': 'Camera access is turned off for this app. Enable it in your phone settings.',
      'camera_unsupported_device': 'This device does not have a usable camera.',
      'camera_unavailable': 'The camera could not be started. Try again or enter the code manually below.',
      'out_of_stock': 'Out of stock',
      'in_stock': 'In stock',
      'snoozed_a_day': 'Snoozed for a day',
      'snooze_a_day': 'Snooze a day',
      'stock_in_note':
          'Use this when new stock arrives outside a formal purchase order — for example a small top-up bought in cash. Add a batch number and expiry date so the app can track it properly.',
      'stock_out_note':
          'Use this to remove stock that was not sold — a sample, a gift, or a correction. Damaged or expired goods should go through Write-offs instead, since those need a manager to approve them.',
      'stock_transfer_note':
          'Use this to move stock from one batch into a new or existing one for the same product, for example after repacking. The total quantity in stock does not change.',
      'quantity_received': 'Quantity received',
      'add_stock': 'Add stock',
      'remove_stock': 'Remove stock',
      'move_stock': 'Move stock',
      'from_batch': 'From batch',
      'to_batch': 'To batch',
      'oldest_first_note': 'leave blank to use the oldest batch automatically',
      'select_product_and_batch': 'Select a product and a batch',
      'stock_updated': 'Stock updated',
      'scan_barcode': 'Scan barcode',
      'align_barcode_in_frame': 'Align the barcode within the frame',
      'enter_code_manually': 'Enter code manually',
      'torch_unavailable': 'Torch is not available on this device',
      'scan': 'Scan',
      'scan_to_add': 'Scan to add',
      'barcode_not_found': 'No product matches that barcode',
      'added_to_cart': 'added to cart',
      'export_pdf': 'Export PDF',
      'export_excel': 'Export Excel',
      'exported': 'Exported',
      'export_failed': 'Export failed',
      'print_receipt': 'Print receipt',
      'share_receipt': 'Share receipt',
      'category': 'Category',
      'brand': 'Brand',
      'no_category': 'No category',
      'no_brand': 'No brand',
      'select_category': 'Select category',
      'select_brand': 'Select brand',
      'add_category': 'Add category',
      'add_brand': 'Add brand',
      'new_category_name': 'New category name',
      'new_brand_name': 'New brand name',
      'units_and_pricing': 'Units & pricing',
      'add_unit': 'Add unit',
      'edit_unit': 'Edit unit',
      'unit_name': 'Unit name',
      'units_per_base': 'Units per base unit',
      'barcode': 'Barcode',
      'retail': 'Retail',
      'wholesale': 'Wholesale',
      'special': 'Special',
      'base': 'Base',
      'base_unit': 'Base unit',
      'stocking_unit': 'Stocking unit',
      'price_history': 'Price history',
      'price': 'Price',
      'reason': 'Reason',
      'price_saved': 'Price saved',
      'remove_unit': 'Remove unit',
      'remove_unit_confirm': 'Remove the unit',
      'optional': 'optional',
      'deleted': 'Deleted',
      'operation_failed': 'Operation failed',
      'enter_valid_number': 'Enter a valid number',
      'no_data': 'No data',
      'set': 'set',
      'inactive': 'Inactive',
      'total_sales': 'Total sales',
      'stock': 'Stock',
      'price_change_logged_note':
          'Every price change is recorded with your name and the time.',
      'batches_and_expiry': 'Batches & expiry',
      'stock_counts': 'Stock counts',
      'stock_count': 'Stock count',
      'new_stock_count': 'New count',
      'no_stock_counts': 'No stock counts yet',
      'nothing_counted_yet': 'Nothing counted yet',
      'count_item': 'Count item',
      'counted_quantity': 'Counted quantity',
      'counted': 'Counted',
      'system': 'System',
      'variance': 'Variance',
      'net_variance': 'Net variance',
      'lines': 'lines',
      'post_count': 'Post count',
      'post_count_confirm':
          'Posting applies every variance to stock. This cannot be undone.',
      'stock_count_posted': 'Stock count posted',
      'posted': 'Posted',
      'draft': 'Draft',
      'cancelled': 'Cancelled',
      'write_offs': 'Write-offs',
      'record_write_off': 'Record write-off',
      'no_write_offs': 'No write-offs',
      'approve_write_off': 'Approve write-off',
      'reject_write_off': 'Reject write-off',
      'approve_removes_stock': 'Approving removes this stock',
      'decision_note': 'Decision note',
      'submitted_for_approval': 'Submitted for approval',
      'write_off_needs_approval_note':
          'Stock is only removed once a manager approves.',
      'approve': 'Approve',
      'reject': 'Reject',
      'approved': 'Approved',
      'rejected': 'Rejected',
      'damage': 'Damage',
      'breakage': 'Breakage',
      'expiry': 'Expiry',
      'theft': 'Theft',
      'other': 'Other',
      'batch': 'Batch',
      'batch_number': 'Batch number',
      'no_batches': 'No batches',
      'search_batches': 'Search batches',
      'receive_stock': 'Receive stock',
      'stock_received': 'Stock received',
      'buying_cost': 'Buying cost',
      'expiry_date': 'Expiry date',
      'expiring_soon': 'Expiring soon',
      'no_expiry': 'No expiry',
      'stock_value': 'Stock value',
      'left': 'left',
      'cost': 'Cost',
      'value': 'Value',
      'not_set': 'Not set',
      'select_product': 'Select a product',
      'note': 'Note',
      'purchasing': 'Purchasing',
      'suppliers': 'Suppliers',
      'supplier': 'Supplier',
      'add_supplier': 'Add supplier',
      'edit_supplier': 'Edit supplier',
      'no_suppliers': 'No suppliers yet',
      'contact': 'Contact',
      'contact_person': 'Contact person',
      'payment_terms': 'Terms',
      'payment_terms_days': 'Payment terms (days)',
      'settled': 'Settled',
      'purchase_orders': 'Purchase orders',
      'no_purchase_orders': 'No purchase orders',
      'supplier_invoices': 'Supplier invoices',
      'no_supplier_invoices': 'No invoices',
      'supplier_invoice_number': 'Supplier invoice no.',
      'receive_goods': 'Receive goods',
      'goods_received': 'Goods received',
      'invoice': 'Invoice',
      'select_supplier_and_product': 'Select a supplier and a product',
      'payment_recorded': 'Payment recorded',
      'pay': 'Pay',
      'received': 'Received',
      'customers_and_credit': 'Customers & credit',
      'credit_settings': 'Credit settings',
      'credit_limit': 'Credit limit',
      'available': 'Available',
      'owes': 'Owes',
      'over_limit': 'Over limit',
      'near_limit': 'Near limit',
      'blocked': 'Blocked',
      'block_customer': 'Block this customer',
      'block_customer_note': 'A blocked customer cannot take new credit.',
      'block_reason': 'Reason for blocking',
      'debtors_ageing': 'Debtors ageing',
      'no_debtors': 'Nobody owes anything',
      'total_owed': 'Total owed',
      'oldest': 'Oldest',
      'search_customers': 'Search customers',
      'statement': 'Statement',
      'opening': 'Opening',
      'closing': 'Closing',
      'charges': 'Charges',
      'period': 'Period',
      'no_transactions': 'No transactions in this period',
      'receive_payment': 'Receive payment',
      'daily_cash': 'Daily cash',
      'payment_allocation_note':
          'The payment is applied to the oldest unpaid invoices first.',
      'unallocated': 'Unallocated',
      'open_session': 'Open session',
      'close_session': 'Close session',
      'cash_session': 'Cash session',
      'no_cash_sessions': 'No cash sessions',
      'opening_float': 'Opening float',
      'expected_cash': 'Expected cash',
      'counted_cash': 'Counted cash',
      'expenses': 'Expenses',
      'no_expenses': 'No expenses recorded',
      'add_expense': 'Add expense',
      'description': 'Description',
      'difference': 'Difference',
      'short': 'Short',
      'surplus': 'Surplus',
      'balanced': 'Balanced',
      'explain_difference': 'Explain the difference',
      'session_already_open': 'You already have an open session',
      'staff': 'Staff',
      'method': 'Method',
      'cheque': 'Cheque',
      'crates_and_empties': 'Crates & empties',
      'depot_position': 'Depot position',
      'crate_type': 'Crate type',
      'select_crate_type': 'Select a crate type',
      'record_movement': 'Record movement',
      'direction': 'Direction',
      'issued': 'Issued',
      'returned': 'Returned',
      'broken': 'Broken',
      'purchased': 'Purchased',
      'held': 'held',
      'out': 'out',
      'out_with_customers': 'Out with customers',
      'deposit_at_risk': 'Deposit at risk',
      'no_crate_movements': 'No crate movements yet',
      'no_customer_crates': 'No customer is holding crates',
      'crates_separate_note': 'Crates are tracked separately from money owed.',
      'returns_and_parked': 'Returns & parked',
      'returns': 'Returns',
      'no_returns': 'No returns',
      'parked_sales': 'Parked sales',
      'no_parked_sales': 'No parked sales',
      'resume': 'Resume',
      'discard': 'Discard',
      'return': 'Return',
      'cancellation': 'Cancellation',
      'deliveries': 'Deliveries',
      'dispatch': 'Dispatch',
      'no_dispatches': 'No dispatches',
      'load_vehicle': 'Load vehicle',
      'route': 'Route',
      'loaded': 'Loaded',
      'sold': 'Sold',
      'on_route': 'On route',
      'reconciled': 'Reconciled',
      'reconcile': 'Reconcile',
      'returned_quantity': 'Returned quantity',
      'cash_expected': 'Cash expected',
      'cash_returned': 'Cash returned',
      'reconciled_balanced': 'Reconciled and balanced',
      'load_removes_stock_note':
          'Loading removes this stock from the depot now.',
      'reconcile_note': 'Unsold stock returns to the depot when you reconcile.',
      'insufficient_stock_or_failed': 'Not enough stock, or the request failed',
      'no_reports': 'No reports available',
      'report_failed': 'The report could not be produced',
      'no_data_for_period': 'No data for this period',
      'rows': 'Rows',
      'alerts': 'Alerts',
      'no_alerts': 'Nothing needs attention',
      'open_alerts': 'Open alerts',
      'critical': 'Critical',
      'warning': 'Warning',
      'info': 'Info',
      'acknowledge': 'Acknowledge',
      'depot_settings': 'Depot settings',
      'audit_trail': 'Audit trail',
      'no_audit_entries': 'Nothing recorded yet',
      'depot_details': 'Depot details',
      'depot_name': 'Depot name',
      'invoicing': 'Invoicing',
      'invoice_prefix': 'Invoice prefix',
      'next_invoice_number': 'Next invoice number',
      'tax_percent': 'Tax %',
      'limits_and_thresholds': 'Limits & thresholds',
      'max_discount_percent': 'Max discount %',
      'large_discount_percent': 'Large discount %',
      'low_stock_threshold': 'Low stock threshold',
      'expiry_alert_days': 'Expiry alert (days)',
      'overdue_alert_days': 'Overdue alert (days)',
      'status': 'Status',
      // General
      'app_name': 'All in One',
      'dashboard': 'Dashboard',
      'settings': 'Settings',
      'profile': 'Profile',
      'logout': 'Logout',
      'login': 'Login',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'cancel': 'Cancel',
      'lipisha': 'Billing',
      'mali': 'Mali',
      'mkataba': 'Contracts',
      'zaidi': 'More',
      'save': 'Save',
      'edit': 'Edit',
      'delete': 'Delete',
      'confirm': 'Confirm',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'refresh': 'Refresh',

      // Settings Screen
      'user_profile': 'User Profile',
      'notifications': 'Notifications',
      'notifications_subtitle': 'Manage app notifications',
      'language': 'Language',
      'language_subtitle': 'Choose app language',
      'security': 'Security',
      'security_subtitle': 'Security settings',
      'backup': 'Backup',
      'backup_subtitle': 'Backup and restore data',
      'about_app': 'About App',
      'about_app_subtitle': 'App information',
      'help': 'Help',
      'help_subtitle': 'Get help using the app',
      'logout_confirm': 'Are you sure you want to logout?',
      'version': 'Version',
      'app_description': 'Motorcycle business management app',
      'copyright': '© 2024 All in One',

      // Users management
      'users': 'Users',
      'users_subtitle': 'Manage application users',
      'users_management': 'Users Management',
      'create_user': 'Create User',
      'full_name': 'Full Name',
      'role': 'Role',
      'active': 'Active',
      'expiring': 'Expiring',
      'expired': 'Expired',
      'reset_password': 'Reset Password',
      'user_created_successfully': 'User created successfully',
      'password_reset_successfully': 'Password reset successfully',
      'default_password_note':
          'Default password will be the LAST surname in CAPITAL letters (e.g., Samwel Mahenye Magaiwa => "MAGAIWA").',

      // Language Selection
      'select_language': 'Select Language',
      'english': 'English',
      'swahili': 'Kiswahili',
      'language_changed': 'Language changed successfully',

      // Notifications Settings
      'push_notifications': 'Push Notifications',
      'email_notifications': 'Email Notifications',
      'payment_alerts': 'Payment Alerts',
      'debt_reminders': 'Debt Reminders',
      'system_updates': 'System Updates',

      // Security Settings
      'change_password': 'Change Password',
      'two_factor_auth': 'Two Factor Authentication',
      'login_history': 'Login History',
      'current_password': 'Current Password',
      'new_password': 'New Password',
      'confirm_password': 'Confirm Password',
      'password_changed': 'Password changed successfully',
      'two_factor_enabled_msg': 'Two-factor enabled',
      'two_factor_disabled_msg': 'Two-factor disabled',
      'no_login_history': 'No login history found.',
      'failed_to_update': 'Failed to update',

      // Backup Settings
      'auto_backup': 'Auto Backup',
      'backup_now': 'Backup Now',
      'restore_data': 'Restore Data',
      'last_backup': 'Last Backup',
      'backup_successful': 'Backup completed successfully',
      'restore_successful': 'Data restored successfully',

      // Dashboard
      'daily_revenue': 'Daily Revenue',
      'weekly_revenue': 'Weekly Revenue',
      'monthly_revenue': 'Monthly Revenue',
      'total_revenue': 'Total Revenue',
      'drivers': 'Drivers',

      // Receipts details/viewer additions
      'receipt_details': 'Receipt Details',
      'receipt': 'Receipt',
      'receipt_number': 'Receipt Number',
      'payment_id': 'Payment ID',
      // Receipt status labels
      'receipt_status_generated': 'Generated',
      'receipt_status_sent': 'Sent',
      'receipt_status_cancelled': 'Cancelled',
      'receipt_status_pending': 'Pending',
      'generated_date': 'Generated Date',
      'payment_period': 'Payment Period',
      'debt_on_dates': 'Debt on dates',
      'step_1_generate_receipt': 'Step 1: Generate Receipt',
      'press_below_to_generate_receipt':
          'Press below to generate the receipt for this payment.',
      'receipt_generated_you_can_send':
          'Receipt generated. You can send it now.',
      'already_generated': 'Already Generated',
      'generating': 'Generating...',
      'receipt_generated': 'Receipt generated!',
      'receipt_already_generated_for_payment':
          'Receipt already generated for this payment!',
      'failed_to_generate_receipt': 'Failed to generate receipt',
      'step_2_send_receipt': 'Step 2: Send Receipt',
      'recipient_email': 'Recipient Email',
      'recipient_phone': 'WhatsApp/SMS Phone Number',
      'sending': 'Sending...',
      'sent': 'Sent',
      'send_receipt': 'Send Receipt',
      'after_sending_status_will_change':
          'After sending, the transaction status will change to “receipt issued.”',
      'missing_receipt_id': 'Missing receipt identifier',
      'enter_contact_info': 'Enter contact info (phone or email)',
      'receipt_sent': 'Receipt sent!',
      'failed_to_send_receipt': 'Failed to send receipt',
      'total_payment': 'Total Payment',
      'trips': 'Trips',
      'outstanding_info_message':
          'Outstanding debt details will be included in the sent receipt message.',
      'send_info': 'Send Info',
      'sent_date': 'Sent Date',
      'sent_to': 'Sent To',
      'resend_receipt': 'Resend Receipt',
      'phone_or_email': 'Phone Number or Email',
      'phone_or_email_required': 'Enter phone number or email',
      'send_again': 'Send Again',
      'receipt_resent': 'Receipt resent!',

      // Payments (record payment flow)
      'record_payment': 'Record Payment',
      'record_payment_subtitle': 'Select a driver then record their payment',
      'select_payment_days': 'Select Payment Days',
      'driver_has_no_debt': 'This driver has no outstanding debt',
      'vehicles': 'Vehicles',
      'receipts_generated': 'Receipts Generated',
      'pending_receipts': 'Pending Receipts',
      'unpaid_debts': 'Unpaid Debts',

      // Receipts
      'receipts': 'Receipts',
      'generate_receipt': 'Generate Receipt',
      'pending': 'Pending',
      'all': 'All',
      'receipt_management': 'Receipt Management',
      'generate_and_send_receipts': 'Generate and send receipts to drivers',
      'no_pending_receipts': 'No pending receipts',
      'no_receipts_generated': 'No receipts generated',
      'receipts_list_empty': 'You will see all receipts here',
      'all_payments_have_receipts':
          'All payments already have receipts generated',

      // Debts records filters and summary (transport)
      'filter_unpaid_only': 'Unpaid only',
      'filter_paid_only': 'Paid only',
      'summary_total_debt': 'Total Debt',
      'summary_unpaid_days': 'Unpaid days',
      'last_payment': 'Last payment',
      'paid_total': 'Paid total',
      'unpaid_total': 'Unpaid total',

      // Common Buttons/Actions
      'view_details': 'View Details',
      'view_all': 'View All',
      'add_new': 'Add New',
      'search': 'Search',
      'filter': 'Filter',
      'export': 'Export',
      'import': 'Import',
      'print': 'Print',
      'share': 'Share',
      'send': 'Send',

      // Dashboard card menu items and actions
      'drivers_who_paid': 'Drivers Who Paid',
      'revenue_breakdown': 'Revenue Breakdown',
      'export_data': 'Export Data',
      'import_data': 'Import Data',
      'current_value': 'Current Value',
      'close': 'Close',
      'process_pending_receipts': 'Process Pending Receipts',
      'confirm_process_pending_receipts':
          'Are you sure you want to process all pending receipts?',
      'process': 'Process',
      'pending_receipts_processed': 'Pending receipts processed',
      'send_payment_reminders': 'Send Payment Reminders',
      'send_reminders': 'Send Reminders',
      'confirm_send_reminders': 'Send reminders to all unpaid drivers?',
      'payment_reminders_sent': 'Payment reminders sent',
      'confirm_export_data': 'Export data for',
      'data_exported_successfully': 'Data exported successfully',
      'menu': 'Menu',
      'active_drivers_only': 'Active Drivers Only',
      'all_vehicles': 'All Vehicles',
      'active_vehicles_only': 'Active Vehicles Only',
      'all_receipts': 'All Receipts',
      'manage_vehicles': 'Manage Vehicles',

      // Extra dashboard titles/descriptions used by cards
      'payments_with_receipts': 'Payments with Receipts',
      'payments_with_receipts_desc':
          'Number of payments that already have receipts.',
      'paid_awaiting_receipts': 'Paid Awaiting Receipts',
      'paid_awaiting_receipts_desc':
          'Payments that are paid and waiting for receipt generation.',
      'unpaid_payments': 'Unpaid Payments',
      'unpaid_payments_desc': 'Payments that are still unpaid.',
      'daily_revenue_desc': 'Revenue collected today.',
      'weekly_revenue_desc': 'Revenue collected this week.',
      'monthly_revenue_desc': 'Revenue collected this month.',
      'drivers_desc': 'Total number of registered drivers.',
      'vehicles_desc': 'Total number of registered vehicles.',
      'additional_card_info': 'Additional information.',

      // Navigation Drawer (additional entries)
      'payments': 'Payments',
      'debt_records': 'Debt Records',
      'analytics': 'Analytics',
      'reports': 'Reports',
      'reminders': 'Reminders',
      'communications': 'Communications',
      'loading_dashboard': 'Loading Dashboard...',
      // Driver dashboard common labels
      'driver_payment_stats': 'Payment Statistics',
      'quick_actions': 'Quick Actions',
      'payment_history': 'Payment History',
      'today': 'Today',
      'week': 'Week',
      'month': 'Month',
      'your_vehicle': 'Your Vehicle',
      'plate_number': 'Plate',
      'status_active': 'Active',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'status_expired': 'Expired',
      // Welcome and reminders
      'welcome': 'Welcome',
      // Agreement labels
      'agreement_total_title': 'Contract Total to Complete',
      'agreement_total_subtitle': 'Amount required to complete the contract',
      'agreement_daily_title': 'Daily Rental Amount',
      'agreement_daily_subtitle': 'Amount to pay per Dei Waka agreement',
      // Driver pages
      'my_receipts': 'My Receipts',
      'no_receipts': 'No receipts',
      'no_reminders': 'No reminders',
      'try_again': 'Try Again',
      'amount': 'Amount',
      'driver': 'Driver',
      'vehicle': 'Vehicle',
      'date': 'Date',
      'covered_days': 'Covered Days',
      'remarks': 'Remarks',
      'payment': 'Payment',
      'debt_clearance': 'Debt Clearance',
      'days': 'Days',
      'no_debt': 'No debt',
      'has_debt': 'You still have debt',
      'total_debt_label': 'Total debt',
      // Reminders/Debts (driver)
      'outstanding_debts': 'Outstanding Debts',
      'total_outstanding': 'Total Outstanding',
      'due_date': 'Due Date',
      'days_overdue': 'Days Overdue',

      // Drivers Management Screen
      'drivers_management': 'Drivers Management',
      'add_driver': 'Add Driver',
      'driver_name': 'Driver Name',
      'driver_phone': 'Phone Number',
      'driver_email': 'Email Address',
      'driver_license': 'License Number',
      'driver_status': 'Status',
      'active_driver': 'Active',
      'inactive_driver': 'Inactive',
      'edit_driver': 'Edit Driver',
      'delete_driver': 'Delete Driver',
      'driver_details': 'Driver Details',
      'total_drivers': 'Total Drivers',
      'active_drivers': 'Active Drivers',
      'driver_added_successfully': 'Driver added successfully',
      'driver_updated_successfully': 'Driver updated successfully',
      'driver_deleted_successfully': 'Driver deleted successfully',
      'confirm_delete_driver': 'Are you sure you want to delete this driver?',
      'no_drivers_found': 'No drivers found',
      'search_drivers': 'Search drivers...',

      // Vehicles Management Screen
      'vehicles_management': 'Vehicles Management',
      'add_vehicle': 'Add Vehicle',
      'vehicle_plate': 'Plate Number',
      'vehicle_model': 'Vehicle Model',
      'vehicle_year': 'Year',
      'vehicle_type': 'Vehicle Type',
      'vehicle_status': 'Status',
      'active_vehicle': 'Active',
      'inactive_vehicle': 'Inactive',
      'edit_vehicle': 'Edit Vehicle',
      'delete_vehicle': 'Delete Vehicle',
      'vehicle_details': 'Vehicle Details',
      'total_vehicles': 'Total Vehicles',
      'active_vehicles': 'Active Vehicles',
      'vehicle_added_successfully': 'Vehicle added successfully',
      'vehicle_updated_successfully': 'Vehicle updated successfully',
      'vehicle_deleted_successfully': 'Vehicle deleted successfully',
      'confirm_delete_vehicle': 'Are you sure you want to delete this vehicle?',
      'no_vehicles_found': 'No vehicles found',
      'search_vehicles': 'Search vehicles...',

      // Payments Screen
      'payments_management': 'Payments Management',
      'payment_amount': 'Amount',
      'payment_date': 'Payment Date',
      'payment_method': 'Payment Method',
      'payment_status': 'Status',
      'payment_reference': 'Reference',
      'payment_driver': 'Driver',
      'payment_vehicle': 'Vehicle',
      'add_payment': 'Add Payment',
      'edit_payment': 'Edit Payment',
      'delete_payment': 'Delete Payment',
      'payment_details': 'Payment Details',
      'total_payments': 'Total Payments',
      'paid_payments': 'Paid',
      'pending_payments': 'Pending',
      'payment_added_successfully': 'Payment added successfully',
      'payment_updated_successfully': 'Payment updated successfully',
      'payment_deleted_successfully': 'Payment deleted successfully',
      'confirm_delete_payment': 'Are you sure you want to delete this payment?',
      'no_payments_found': 'No payments found',
      'search_payments': 'Search payments...',
      'cash': 'Cash',
      'mobile_money': 'Mobile Money',
      'bank_transfer': 'Bank Transfer',
      'paid': 'Paid',
      'overdue': 'Overdue',

      // Debts Management Screen
      'debts_management': 'Debts Management',
      'debt_amount': 'Debt Amount',
      'debt_date': 'Debt Date',
      'debt_due_date': 'Due Date',
      'debt_status': 'Status',
      'debt_driver': 'Driver',
      'debt_description': 'Description',
      'add_debt': 'Add Debt',
      'edit_debt': 'Edit Debt',
      'delete_debt': 'Delete Debt',
      'debt_details': 'Debt Details',
      'total_debts': 'Total Debts',
      'paid_debts': 'Paid Debts',
      'debt_added_successfully': 'Debt added successfully',
      'debt_updated_successfully': 'Debt updated successfully',
      'debt_deleted_successfully': 'Debt deleted successfully',
      'confirm_delete_debt': 'Are you sure you want to delete this debt?',
      'no_debts_found': 'No debts found',
      'search_debts': 'Search debts...',
      'mark_as_paid': 'Mark as Paid',
      'mark_as_unpaid': 'Mark as Unpaid',

      // Analytics Screen
      'analytics_dashboard': 'Analytics Dashboard',
      'revenue_analytics': 'Revenue Analytics',
      'driver_analytics': 'Driver Analytics',
      'vehicle_analytics': 'Vehicle Analytics',
      'payment_analytics': 'Payment Analytics',
      'performance_metrics': 'Performance Metrics',
      'revenue_trends': 'Revenue Trends',
      'top_drivers': 'Top Drivers',
      'active_vehicles_chart': 'Active Vehicles',
      'monthly_comparison': 'Monthly Comparison',
      'yearly_comparison': 'Yearly Comparison',
      'export_analytics': 'Export Analytics',
      'date_range': 'Date Range',
      'from_date': 'From Date',
      'to_date': 'To Date',
      'apply_filter': 'Apply Filter',
      'clear_filter': 'Clear Filter',

      // Reports Screen
      'reports_dashboard': 'Reports Dashboard',
      'generate_report': 'Generate Report',
      'driver_report': 'Driver Report',
      'vehicle_report': 'Vehicle Report',
      'payment_report': 'Payment Report',
      'debt_report': 'Debt Report',
      'revenue_report': 'Revenue Report',
      'monthly_report': 'Monthly Report',
      'yearly_report': 'Yearly Report',
      'custom_report': 'Custom Report',
      'report_type': 'Report Type',
      'report_period': 'Report Period',
      'report_format': 'Report Format',
      'pdf_format': 'PDF',
      'excel_format': 'Excel',
      'csv_format': 'CSV',
      'download_report': 'Download Report',
      'email_report': 'Email Report',
      'report_generated_successfully': 'Report generated successfully',
      'report_generation_failed': 'Report generation failed',

      // Reminders Screen
      'reminders_management': 'Reminders Management',
      'add_reminder': 'Add Reminder',
      'reminder_title': 'Reminder Title',
      'reminder_message': 'Message',
      'reminder_date': 'Reminder Date',
      'reminder_time': 'Reminder Time',
      'reminder_type': 'Type',
      'payment_reminder': 'Payment Reminder',
      'maintenance_reminder': 'Maintenance Reminder',
      'general_reminder': 'General Reminder',
      'reminder_status': 'Status',
      'active_reminder': 'Active',
      'completed_reminder': 'Completed',
      'edit_reminder': 'Edit Reminder',
      'delete_reminder': 'Delete Reminder',
      'reminder_details': 'Reminder Details',
      'total_reminders': 'Total Reminders',
      'active_reminders': 'Active Reminders',
      'completed_reminders': 'Completed',
      'reminder_added_successfully': 'Reminder added successfully',
      'reminder_updated_successfully': 'Reminder updated successfully',
      'reminder_deleted_successfully': 'Reminder deleted successfully',
      'confirm_delete_reminder':
          'Are you sure you want to delete this reminder?',
      'no_reminders_found': 'No reminders found',
      'search_reminders': 'Search reminders...',
      'mark_as_completed': 'Mark as Completed',
      'send_reminder': 'Send Reminder',

      // Communications Screen
      'communications_management': 'Communications',
      'send_message': 'Send Message',
      'message_title': 'Message Title',
      'message_content': 'Message Content',
      'message_recipients': 'Recipients',
      'all_drivers': 'All Drivers',
      'selected_drivers': 'Selected Drivers',
      'message_type': 'Message Type',
      'sms_message': 'SMS',
      'email_message': 'Email',
      'push_notification': 'Push Notification',
      'send_immediately': 'Send Immediately',
      'schedule_message': 'Schedule Message',
      'scheduled_date': 'Scheduled Date',
      'scheduled_time': 'Scheduled Time',
      'message_history': 'Message History',
      'sent_messages': 'Sent Messages',
      'scheduled_messages': 'Scheduled Messages',
      'message_status': 'Status',
      'message_sent': 'Sent',
      'message_scheduled': 'Scheduled',
      'message_failed': 'Failed',
      'message_delivered': 'Delivered',
      'message_sent_successfully': 'Message sent successfully',
      'message_scheduled_successfully': 'Message scheduled successfully',
      'message_failed_to_send': 'Failed to send message',
      'no_messages_found': 'No messages found',
      'search_messages': 'Search messages...',
      'select_recipients': 'Select Recipients',

      // Login Screen
      'login_successful': 'Login successful!',
      'login_failed': 'Login failed',
      'login_error': 'Error during login: ',
      'demo_credentials_filled': 'Demo credentials filled',
      'database_credentials_filled': 'Database credentials filled',
      'forgot_password': 'Forgot Password?',
      'forgot_password_message':
          'Password reset feature is under development. For now, use demo credentials or contact the administrator.',
      'use_database': 'Use Database',
      'email': 'Email',
      'password': 'Password',
      'phone_number': 'Phone Number',
      'signin': 'Sign In',
      'welcome_back': 'Welcome Back',
      'signin_subtitle': 'Sign in to continue to your account',

      // Service selection
      'select_service': 'Select Service',
      'select_service_subtitle': 'Choose what you want to manage today',
      'inventory_service': 'Inventory',
      'rental_service': 'All in One',
      'transport_service': 'Transport',
      'coming_soon': 'Coming soon…',
      'switch_service': 'Switch Service',

      // Inventory module
      'inventory_dashboard': 'Inventory Dashboard',
      'products': 'Products',
      'stock_levels': 'Stock Levels',
      'stock_in_out_transfer': 'Stock In/Out/Transfer',
      'stock_in': 'Stock In',
      'stock_out': 'Stock Out',
      'stock_transfer': 'Transfer',
      'sales': 'Sales',
      'total_sales_today': 'Total Sales Today',
      'profit_today': 'Profit (Today)',
      'profit_week': 'Profit (Week)',
      'profit_month': 'Profit (Month)',
      'sales_trend': 'Sales Trend',
      'low_stock': 'Low Stock',
      'quantity': 'Quantity',
      'min_stock': 'Min Stock',
      'warehouse': 'Warehouse',
      'sku': 'SKU',
      'product': 'Product',
      'reference': 'Reference',
      'from_warehouse': 'From Warehouse',
      'to_warehouse': 'To Warehouse',
      'saved': 'Saved',
      'add_product': 'Add Product',
      'search_products': 'Search products…',
      'create_sale_pos': 'Create Sale (POS)',
      'create_sale_hint': 'Add products, set quantities, choose payment mode.',
      'add_products': 'Add Products',
      'checkout': 'Checkout',
      'recent_sales': 'Recent Sales',
      'items': 'items',
      'payment_due': 'Payment Due',
      'payment_due_desc': 'A payment is due soon.',
      'low_stock_desc': 'Stock level is below the minimum.',
      'mark_done': 'Mark Done',
      'snooze': 'Snooze',
      'open': 'Open',
      'snoozed': 'Snoozed',
      'done': 'Done',

      // POS / Sales
      'payment_mode': 'Payment Mode',
      'debt': 'Debt',
      'partial': 'Partial',
      'customer': 'Customer',
      'customer_required': 'Customer is required for Debt/Partial',
      'add_to_cart': 'Add to Cart',
      'qty': 'Qty',
      'unit_price': 'Unit Price',
      'subtotal': 'Subtotal',
      'total': 'Total',
      'profit': 'Profit',
      'paid_amount': 'Paid Amount',
      'select_customer': 'Select customer',
      'cannot_negative_stock': 'Operation would make stock negative',
      'balance': 'Balance',
      'add_customer': 'Add Customer',
      'customer_name': 'Customer Name',
      'address': 'Address',

      // Rental navigation
      'rental_dashboard': 'Rental Dashboard',
      'tenants': 'Tenants',
      'properties': 'Properties',
      'rent_payments': 'Rent Payments',
      'arrears': 'Arrears',
      'billing_reports': 'Billing Reports',
      'sms_history': 'SMS History',
      'lease_agreements': 'Lease Agreements',
      'lease_templates': 'Lease Templates',
      'tenant_self_service': 'My Account',
      'helpdesk': 'Helpdesk',
      'helpdesk_subtitle': 'View guides and contact support',

      // Rental Onboarding
      'register_tenant': 'Register Tenant',
      'step': 'Step',
      'personal_info': 'Personal Information',
      'emergency_contact': 'Emergency Contact',
      'identification': 'Identification',
      'employment': 'Employment',
      'history': 'Rental History',
      'peeps': 'Occupants & Pets',
      'terms': 'Terms & Property',
      'contact_identity': 'Contact & Identity',
      'employment_history': 'Job & History',
      'living_property': 'Living & Property',
      'media': 'Media',
      'terms_conditions': 'Terms & Conditions',
      'first_name': 'First Name',
      'last_name': 'Last Name',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'birth_date': 'Birth Date',
      'nida_id': 'NIDA / ID',
      'phone_no': 'Phone No',
      'email_address': 'Email Address',
      'contact_name': 'Contact Name',
      'relationship': 'Relationship',
      'id_number': 'ID / Passport No',
      'state_issued': 'State Issued',
      'exp_date': 'Exp Date',
      'upload_id': 'Upload ID',
      'employer': 'Employer',
      'job_title': 'Job Title',
      'employment_duration': 'Employment Duration',
      'work_no': 'Work No',
      'currently_employed': 'Currently Employed',
      'prev_address': 'Previous Address',
      'stay_duration': 'Stay Duration',
      'reason_leaving': 'Reason for Leaving',
      'landlord_name': 'Landlord Name',
      'landlord_phone': 'Landlord Phone',
      'adults_count': 'Adults',
      'children_count': 'Children',
      'others_live_here': 'Will others live here?',
      'pet_type': 'Pet Type',
      'breed': 'Breed',
      'pet_age': 'Pet Age',
      'pet_weight': 'Weight',
      'others_stay': 'Others will stay?',
      'additional_notes': 'Additional Notes',
      'select_property': 'Select Property',
      'select_house': 'Select House',
      'start_date': 'Start Date',
      'rent_amount': 'Rent Amount',
      'deposit_amount': 'Security Deposit Amount',
      'deposit': 'Security Deposit',
      'deposit_exceeds_rent': 'Deposit cannot exceed rent',
      'capture_tenant_photo': 'Capture Tenant Photo',
      'photo_attached': 'Photo attached successfully',
      'tap_to_upload': 'Tap to upload photo',
      'accept_terms': 'I accept Terms & Conditions',
      'agree_privacy': 'I agree to the Privacy Policy',
      'previous': 'Previous',
      'next_step': 'Next Step',
      'submit': 'Submit',
      'tenant_onboarded_success': 'Tenant onboarded successfully!',
      'coming_soon_arrears': 'Arrears Tracking Coming Soon',
      'coming_soon_tenants': 'Tenants List Coming Soon',
      'coming_soon_receipts': 'Rent Receipts Coming Soon',
      'failed_to_onboard': 'Failed to onboard tenant. Try again.',
      'select_house_error': 'Please select a house in Step 7',
      'accept_terms_error': 'Please accept Terms and Privacy Policy',
      'loading_properties': 'Loading properties...',
      'no_properties_found': 'No properties found',
      'houses': 'Houses',
      'occupancy': 'Occupancy',
      'welcome_landlord': 'Welcome, Landlord',
      'add_property': 'Add Property',
      'view_bills': 'View Bills',
      'onboard_tenant': 'Onboard Tenant',
      'my_properties': 'My Properties',
      'see_all': 'See All',
      'rent_billing': 'Rent Billing',
      'no_bills_found': 'No bills found',
      'unpaid': 'Unpaid',
      'due': 'Due',
      'tap_to_pay': 'Tap to Pay',
      'amount_paid_tsh': 'Amount Paid (Tsh)',
      'confirm_payment': 'Confirm Payment',
      'recording_payment_for': 'Recording payment for',
      'payment_success': 'Payment recorded successfully!',
      'payment_failed': 'Failed to record payment.',
      'digital_receipt': 'Digital Receipt',
      'payment_successful': 'Payment Successful',
      'receipt_prefix': 'Receipt #',
      'sharing_success': 'Receipt shared successfully!',
      'printing_msg': 'Sending to printer...',
      'thank_you_payment': 'Thank you for your payment!',
      'mapato_rental_service': 'All in One',
      'maintenance_end_date': 'Completion Date',
      'available_from': 'Available from',
      'under_maintenance': 'Under Maintenance',

      // Rental Property Management
      'property_details': 'Property Details',
      'edit_property': 'Edit Property',
      'maintenance': 'Maintenance',
      'no_properties': 'No properties yet',
      'add_property_hint': 'Start by adding your first rental property.',
      'occupied': 'Occupied',
      'vacant': 'Vacant',
      'basic_information': 'Basic Information',
      'property_name': 'Property Name',
      'property_type': 'Property Type',
      'configuration': 'Configuration',
      'billing_cycle': 'Billing Cycle',
      'property_created': 'Property created successfully!',
      'property_updated': 'Property updated successfully!',
      'field_required': 'This field is required',
      'total_houses': 'Total Houses',
      'blocks': 'Blocks',
      'recent_payments': 'Recent Payments',
      'no_payments': 'No payments',
      'active_leases': 'Active',
      'expiring_leases': 'Expiring Soon',
      'all_leases': 'All',
      'no_leases_found': 'No agreements found',
      'house': 'House',
      'lease_wizard': 'Lease Agreement Wizard',
      'step_selection': 'Selection',
      'step_terms': 'Terms',
      'step_payments': 'Payments',
      'step_utilities': 'Utilities',
      'step_rules': 'Rules',
      'step_review': 'Review',
      'complete': 'Complete',
      'rent_monthly': 'Monthly Rent',
      'security_deposit': 'Security Deposit',
      'deposit_paid': 'Deposit Paid',
      'advance_months': 'Advance Rent (Months)',
      'total_prepaid': 'Total Rent Prepaid',
      'paid_until': 'Paid Until',
      'default_landlord_obligations':
          '1. Maintain the property in a habitable condition.\n2. Repair structural defects.\n3. Respect tenant privacy.',
      'default_tenant_obligations':
          '1. Pay rent on time.\n2. Keep the premises clean.\n3. Avoid excessive noise.',
      'default_termination_policy':
          'Either party may terminate this agreement by giving 30 days written notice.',
      'due_day': 'Due Day',
      'grace_period': 'Grace Period',
      'late_fee_type': 'Late Fee Type',
      'auto_renew': 'Auto-Renew',
      'house_details': 'House Details',
      'tenant_obligations': 'Tenant Obligations',
      'landlord_obligations': 'Landlord Obligations',
      'termination_policy': 'Termination Policy',
      'review_lease': 'Review Lease Terms',
      'utilities_water': 'Water',
      'utilities_electricity': 'Electricity',
      'service_charge': 'Service Charge',
      'parking_space': 'Parking Space',
      'wizard_complete_msg': 'Press "Complete" to create this official lease.',
      'base_rent': 'Base Rent',
      'base_deposit': 'Base Deposit',
      'utility_billing': 'Utility Billing',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'gps_location': 'GPS Location',
      'ownership_details': 'Ownership Details',
      'floor': 'Floor',
      'area_sqm': 'Area (sqm)',
      'notes': 'Notes',
      'confirm_delete_property': 'Delete Property?',
      'confirm_delete_house': 'Delete House?',
      'cannot_be_undone': 'This action cannot be undone.',
      'property_delete_success': 'Property deleted successfully',
      'property_delete_failed': 'Failed to delete property',
      'house_delete_success': 'House deleted successfully',
      'house_delete_failed': 'Failed to delete house',
      'unit_number': 'Unit Number',
      'edit_house': 'Edit House',
      'update': 'Update',
      'signature_upload': 'Signature / Signed Contract Upload',
      'upload_signed_copy': 'Upload Signed Copy (PDF/Image)',
      'please_select_tenant_house': 'Please select a tenant and house',
      'lease_created_success': 'Lease created successfully',
      'lease_creation_failed': 'Failed to create lease',
      'retry': 'Retry',
      'select': 'Select',
      'change_image': 'Change Image',
      'gallery': 'Gallery',
      'camera': 'Camera',
      'months_covered': 'Months Covered',
      'tenant': 'Tenant',
      'property': 'Property',
      'amount_paid': 'Amount Paid',

      // House Features
      'add_house': 'Add House',
      'register_house': 'Register House',
      'basic_info': 'Basic Information',
      'house_number': 'House Number',
      'house_type': 'Type',
      'house_status': 'Status',
      'house_features': 'Interior Features',
      'units_section': 'Units (Rooms/Doors)',
      'total_units_label': 'Number of Units',
      'unit': 'Unit',
      'name_units_hint': 'Give each unit a unique name or number',
      'rent_whole_house': 'Rent Whole House?',
      'select_units_prompt': 'Select units included in this agreement',
      'unit_rented': 'Unit Rented',
      'has_fence': 'Has Fence/Wall?',
      'has_tiles': 'Has Floor Tiles?',
      'has_master_bedroom': 'Has Master Bedroom?',
      'has_sitting_room': 'Has Sitting Room?',
      'has_kitchen': 'Has Kitchen?',
      'kitchen_location': 'Kitchen Location',
      'inside': 'Inside',
      'outside': 'Outside',
      'distance_from_road': 'Distance from Main Road',
      'utilities_section': 'Utilities (Water & Electricity)',
      'electricity_meter': 'Electricity Meter',
      'electricity_type': 'Electricity Type',
      'water_meter': 'Water Meter',
      'water_type': 'Water Type',
      'independent': 'Independent',
      'shared': 'Shared',
      'sharing_count': 'How Many Share?',
      'landlord_lives_here': 'Landlord Lives Here?',
      'residence_ownership': 'Residence & Ownership',
      'photos_section': 'House Photos & 3D Preview',
      'photos_hint': 'Take or upload photos to showcase the property.',
      'photos_required': 'At least 1 photo is required (max 5).',
      'add_photos': 'Add Photos',
      'save_house': 'Save House',
      'update_house': 'Update House',
      'invalid_amount': 'Invalid amount',
      'find_dream_home': 'Find Your Dream Home',
      'explore_houses_hint':
          'Explore and find the best rental property for your needs.',
      'search_houses': 'Search houses, locations...',
      'no_houses_available': 'No houses available matching your search.',
      'from_road': 'from road',
      'bedrooms': 'Bedrooms',
      'bathrooms': 'Bathrooms',
      'room': 'Room',
      'apartment': 'Apartment',
      'studio': 'Studio',
      'one_bedroom': '1 Bedroom',
      'two_bedroom': '2 Bedrooms',
      'bedsitter': 'Bedsitter',
      'login_to_manage': 'Login to Manage',
      'filters': 'Filters',
      'reset': 'Reset',
      'rooms': 'Rooms',
      'landlord_status_on': 'Landlord lives on-site',
      'landlord_status_off': 'Landlord lives off-site',
      'apply_filters': 'Apply Filters',
      'image_name': 'Name This Photo',
      'image_name_hint': 'e.g. Front View, Kitchen, Bathroom...',
      'photo': 'Photo',

      // Location Hierarchy
      'country': 'Country',
      'region': 'Region',
      'district': 'District',
      'ward': 'Ward',
      'street': 'Street / Village',
      'place': 'Hamlet',
      'location': 'Location',
      'select_country': 'Select Country',
      'select_region': 'Select Region',
      'select_district': 'Select District',
      'select_ward': 'Select Ward',
      'select_street': 'Select Street/Village',
      'select_place': 'Select Hamlet',
      'update_property': 'Update Property',
      'confirm_vacate': 'Confirm Vacate',
      'vacate_message':
          'Are you sure you want to terminate the agreement and vacate this house?',
      'vacate_success': 'Tenant vacated successfully',
      'vacate_failed': 'Failed to vacate tenant',
      'vacate_house': 'Vacate House',
      'confirm_delete': 'Are you sure you want to delete',
    },
    'sw': {
      'camera_permission_denied': 'Ruhusa ya kamera imezimwa kwa programu hii. Iwashe kwenye mipangilio ya simu.',
      'camera_unsupported_device': 'Kifaa hiki hakina kamera inayoweza kutumika.',
      'camera_unavailable': 'Kamera haikuweza kuanza. Jaribu tena au ingiza namba mwenyewe hapa chini.',
      'out_of_stock': 'Hisa imekwisha',
      'in_stock': 'Ipo hisani',
      'snoozed_a_day': 'Imesitishwa kwa siku moja',
      'snooze_a_day': 'Sitisha kwa siku moja',
      'stock_in_note':
          'Tumia hii wakati hisa mpya inapowasili nje ya oda rasmi ya manunuzi — mfano nyongeza ndogo iliyonunuliwa kwa taslimu. Ongeza namba ya bechi na tarehe ya mwisho ili programu iweze kuifuatilia vizuri.',
      'stock_out_note':
          'Tumia hii kuondoa hisa isiyouzwa — sampuli, zawadi, au marekebisho. Bidhaa zilizoharibika au zilizoisha muda zinapaswa kupitia Hasara za Bidhaa, kwani hizo zinahitaji idhini ya meneja.',
      'stock_transfer_note':
          'Tumia hii kuhamisha hisa kutoka bechi moja kwenda bechi mpya au iliyopo ya bidhaa hiyohiyo, mfano baada ya kufungasha upya. Jumla ya hisa haibadiliki.',
      'quantity_received': 'Idadi iliyopokelewa',
      'add_stock': 'Ongeza hisa',
      'remove_stock': 'Ondoa hisa',
      'move_stock': 'Hamisha hisa',
      'from_batch': 'Kutoka bechi',
      'to_batch': 'Kwenda bechi',
      'oldest_first_note': 'acha wazi kutumia bechi kongwe kiotomatiki',
      'select_product_and_batch': 'Chagua bidhaa na bechi',
      'stock_updated': 'Hisa imesasishwa',
      'scan_barcode': 'Skani baakodi',
      'align_barcode_in_frame': 'Weka baakodi ndani ya fremu',
      'enter_code_manually': 'Ingiza namba mwenyewe',
      'torch_unavailable': 'Tochi haipatikani kwenye kifaa hiki',
      'scan': 'Skani',
      'scan_to_add': 'Skani kuongeza',
      'barcode_not_found': 'Hakuna bidhaa inayolingana na baakodi hiyo',
      'added_to_cart': 'imeongezwa kwenye kikapu',
      'export_pdf': 'Hamisha PDF',
      'export_excel': 'Hamisha Excel',
      'exported': 'Imehamishwa',
      'export_failed': 'Kuhamisha kumeshindikana',
      'print_receipt': 'Chapisha risiti',
      'share_receipt': 'Shiriki risiti',
      'category': 'Jamii',
      'brand': 'Chapa',
      'no_category': 'Hakuna jamii',
      'no_brand': 'Hakuna chapa',
      'select_category': 'Chagua jamii',
      'select_brand': 'Chagua chapa',
      'add_category': 'Ongeza jamii',
      'add_brand': 'Ongeza chapa',
      'new_category_name': 'Jina la jamii mpya',
      'new_brand_name': 'Jina la chapa mpya',
      'purchasing': 'Manunuzi',
      'suppliers': 'Wasambazaji',
      'supplier': 'Msambazaji',
      'add_supplier': 'Ongeza msambazaji',
      'edit_supplier': 'Hariri msambazaji',
      'no_suppliers': 'Hakuna wasambazaji',
      'contact': 'Mawasiliano',
      'contact_person': 'Mtu wa mawasiliano',
      'payment_terms': 'Masharti',
      'payment_terms_days': 'Masharti ya malipo (siku)',
      'settled': 'Imelipwa',
      'purchase_orders': 'Oda za manunuzi',
      'no_purchase_orders': 'Hakuna oda',
      'supplier_invoices': 'Ankara za wasambazaji',
      'no_supplier_invoices': 'Hakuna ankara',
      'supplier_invoice_number': 'Namba ya ankara',
      'receive_goods': 'Pokea bidhaa',
      'goods_received': 'Bidhaa zimepokelewa',
      'invoice': 'Ankara',
      'select_supplier_and_product': 'Chagua msambazaji na bidhaa',
      'payment_recorded': 'Malipo yamerekodiwa',
      'pay': 'Lipa',
      'received': 'Imepokelewa',
      'customers_and_credit': 'Wateja na mikopo',
      'credit_settings': 'Mipangilio ya mkopo',
      'credit_limit': 'Kikomo cha mkopo',
      'available': 'Inapatikana',
      'owes': 'Anadaiwa',
      'over_limit': 'Amezidi kikomo',
      'near_limit': 'Karibu na kikomo',
      'blocked': 'Amezuiwa',
      'block_customer': 'Zuia mteja huyu',
      'block_customer_note': 'Mteja aliyezuiwa hawezi kupata mkopo mpya.',
      'block_reason': 'Sababu ya kuzuia',
      'debtors_ageing': 'Umri wa madeni',
      'no_debtors': 'Hakuna anayedaiwa',
      'total_owed': 'Jumla ya deni',
      'oldest': 'Kongwe',
      'search_customers': 'Tafuta wateja',
      'statement': 'Taarifa',
      'opening': 'Ufunguzi',
      'closing': 'Ufungaji',
      'charges': 'Gharama',
      'period': 'Kipindi',
      'no_transactions': 'Hakuna miamala kipindi hiki',
      'receive_payment': 'Pokea malipo',
      'daily_cash': 'Fedha za siku',
      'payment_allocation_note': 'Malipo hulipia ankara kongwe kwanza.',
      'unallocated': 'Hayajagawiwa',
      'open_session': 'Fungua kipindi',
      'close_session': 'Funga kipindi',
      'cash_session': 'Kipindi cha fedha',
      'no_cash_sessions': 'Hakuna vipindi',
      'opening_float': 'Fedha za kuanzia',
      'expected_cash': 'Fedha inayotarajiwa',
      'counted_cash': 'Fedha iliyohesabiwa',
      'expenses': 'Matumizi',
      'no_expenses': 'Hakuna matumizi',
      'add_expense': 'Ongeza matumizi',
      'description': 'Maelezo',
      'difference': 'Tofauti',
      'short': 'Pungufu',
      'surplus': 'Ziada',
      'balanced': 'Sawa',
      'explain_difference': 'Eleza tofauti',
      'session_already_open': 'Tayari una kipindi kilichofunguliwa',
      'staff': 'Mfanyakazi',
      'method': 'Njia',
      'cheque': 'Hundi',
      'crates_and_empties': 'Makreti na chupa tupu',
      'depot_position': 'Hali ya ghala',
      'crate_type': 'Aina ya kreti',
      'select_crate_type': 'Chagua aina ya kreti',
      'record_movement': 'Rekodi mwendo',
      'direction': 'Mwelekeo',
      'issued': 'Zimetolewa',
      'returned': 'Zimerudishwa',
      'broken': 'Zimevunjika',
      'purchased': 'Zimenunuliwa',
      'held': 'anazo',
      'out': 'nje',
      'out_with_customers': 'Zilizo kwa wateja',
      'deposit_at_risk': 'Dhamana hatarini',
      'no_crate_movements': 'Hakuna mwendo wa makreti',
      'no_customer_crates': 'Hakuna mteja mwenye makreti',
      'crates_separate_note': 'Makreti hufuatiliwa tofauti na deni la fedha.',
      'returns_and_parked': 'Marejesho na zilizohifadhiwa',
      'returns': 'Marejesho',
      'no_returns': 'Hakuna marejesho',
      'parked_sales': 'Mauzo yaliyohifadhiwa',
      'no_parked_sales': 'Hakuna mauzo yaliyohifadhiwa',
      'resume': 'Endelea',
      'discard': 'Tupa',
      'return': 'Rejesho',
      'cancellation': 'Kughairi',
      'deliveries': 'Usafirishaji',
      'dispatch': 'Safari',
      'no_dispatches': 'Hakuna safari',
      'load_vehicle': 'Pakia gari',
      'route': 'Njia',
      'loaded': 'Zimepakiwa',
      'sold': 'Zimeuzwa',
      'on_route': 'Njiani',
      'reconciled': 'Imelinganishwa',
      'reconcile': 'Linganisha',
      'returned_quantity': 'Idadi iliyorudi',
      'cash_expected': 'Fedha inayotarajiwa',
      'cash_returned': 'Fedha iliyorudi',
      'reconciled_balanced': 'Imelinganishwa sawa',
      'load_removes_stock_note': 'Kupakia huondoa hisa hii ghalani sasa.',
      'reconcile_note': 'Hisa isiyouzwa hurudi ghalani unapolinganisha.',
      'insufficient_stock_or_failed': 'Hisa haitoshi, au ombi limeshindikana',
      'no_reports': 'Hakuna ripoti',
      'report_failed': 'Ripoti haikuweza kutolewa',
      'no_data_for_period': 'Hakuna taarifa kipindi hiki',
      'rows': 'Safu',
      'alerts': 'Arifa',
      'no_alerts': 'Hakuna linalohitaji uangalizi',
      'open_alerts': 'Arifa wazi',
      'critical': 'Muhimu sana',
      'warning': 'Onyo',
      'info': 'Taarifa',
      'acknowledge': 'Thibitisha',
      'depot_settings': 'Mipangilio ya ghala',
      'audit_trail': 'Kumbukumbu za mfumo',
      'no_audit_entries': 'Hakuna kumbukumbu',
      'depot_details': 'Taarifa za ghala',
      'depot_name': 'Jina la ghala',
      'invoicing': 'Ankara',
      'invoice_prefix': 'Kianzio cha ankara',
      'next_invoice_number': 'Namba ijayo',
      'tax_percent': 'Kodi %',
      'limits_and_thresholds': 'Vikomo',
      'max_discount_percent': 'Punguzo kubwa %',
      'large_discount_percent': 'Punguzo la juu %',
      'low_stock_threshold': 'Kikomo cha hisa ndogo',
      'expiry_alert_days': 'Arifa ya muda (siku)',
      'overdue_alert_days': 'Arifa ya kuchelewa (siku)',
      'batches_and_expiry': 'Bechi na muda wa matumizi',
      'stock_counts': 'Hesabu za hisa',
      'stock_count': 'Hesabu ya hisa',
      'new_stock_count': 'Hesabu mpya',
      'no_stock_counts': 'Hakuna hesabu za hisa bado',
      'nothing_counted_yet': 'Hakuna kilichohesabiwa bado',
      'count_item': 'Hesabu bidhaa',
      'counted_quantity': 'Idadi iliyohesabiwa',
      'counted': 'Imehesabiwa',
      'system': 'Mfumo',
      'variance': 'Tofauti',
      'net_variance': 'Tofauti jumla',
      'lines': 'safu',
      'post_count': 'Thibitisha hesabu',
      'post_count_confirm':
          'Kuthibitisha kutabadilisha hisa kulingana na tofauti. Haiwezi kurudishwa.',
      'stock_count_posted': 'Hesabu ya hisa imethibitishwa',
      'posted': 'Imethibitishwa',
      'draft': 'Rasimu',
      'cancelled': 'Imeghairiwa',
      'write_offs': 'Hasara za bidhaa',
      'record_write_off': 'Rekodi hasara',
      'no_write_offs': 'Hakuna hasara',
      'approve_write_off': 'Idhinisha hasara',
      'reject_write_off': 'Kataa hasara',
      'approve_removes_stock': 'Kuidhinisha kutaondoa hisa hii',
      'decision_note': 'Maelezo ya uamuzi',
      'submitted_for_approval': 'Imewasilishwa kwa idhini',
      'write_off_needs_approval_note':
          'Hisa huondolewa tu baada ya meneja kuidhinisha.',
      'approve': 'Idhinisha',
      'reject': 'Kataa',
      'approved': 'Imeidhinishwa',
      'rejected': 'Imekataliwa',
      'damage': 'Uharibifu',
      'breakage': 'Kuvunjika',
      'expiry': 'Muda kuisha',
      'theft': 'Wizi',
      'other': 'Nyingine',
      'batch': 'Bechi',
      'batch_number': 'Namba ya bechi',
      'no_batches': 'Hakuna bechi',
      'search_batches': 'Tafuta bechi',
      'receive_stock': 'Pokea hisa',
      'stock_received': 'Hisa imepokelewa',
      'buying_cost': 'Gharama ya ununuzi',
      'expiry_date': 'Tarehe ya mwisho',
      'expiring_soon': 'Karibu kuisha',
      'no_expiry': 'Hakuna tarehe',
      'stock_value': 'Thamani ya hisa',
      'left': 'zimebaki',
      'cost': 'Gharama',
      'value': 'Thamani',
      'not_set': 'Haijawekwa',
      'select_product': 'Chagua bidhaa',
      'units_and_pricing': 'Vipimo na bei',
      'add_unit': 'Ongeza kipimo',
      'edit_unit': 'Hariri kipimo',
      'unit_name': 'Jina la kipimo',
      'units_per_base': 'Idadi kwa kipimo cha msingi',
      'barcode': 'Baakodi',
      'retail': 'Rejareja',
      'wholesale': 'Jumla',
      'special': 'Maalum',
      'base': 'Msingi',
      'base_unit': 'Kipimo cha msingi',
      'stocking_unit': 'Kipimo cha hifadhi',
      'price_history': 'Historia ya bei',
      'price': 'Bei',
      'reason': 'Sababu',
      'price_saved': 'Bei imehifadhiwa',
      'remove_unit': 'Ondoa kipimo',
      'remove_unit_confirm': 'Ondoa kipimo',
      'optional': 'hiari',
      'deleted': 'Imefutwa',
      'operation_failed': 'Operesheni imeshindikana',
      'enter_valid_number': 'Weka namba sahihi',
      'no_data': 'Hakuna taarifa',
      'set': 'imewekwa',
      'inactive': 'Haitumiki',
      'total_sales': 'Mauzo yote',
      'stock': 'Hisa',
      'price_change_logged_note':
          'Kila mabadiliko ya bei hurekodiwa na jina lako na muda.',
      // General
      'app_name': 'All in One',
      'dashboard': 'Dashibodi',
      'settings': 'Mipangilio',
      'profile': 'Wasifu',
      'logout': 'Toka',
      'login': 'Ingia',
      'yes': 'Ndio',
      'no': 'Hapana',
      'ok': 'Sawa',
      'cancel': 'Sitisha',
      'lipisha': 'Lipisha',
      'mali': 'Mali',
      'mkataba': 'Mkataba',
      'zaidi': 'Zaidi',
      'save': 'Hifadhi',
      'edit': 'Hariri',
      'delete': 'Futa',
      'confirm': 'Thibitisha',
      'loading': 'Inapakia...',
      'error': 'Hitilafu',
      'success': 'Imefanikiwa',
      'refresh': 'Onyesha upya',

      // Settings Screen
      'user_profile': 'Wasifu wa Mtumiaji',
      'notifications': 'Arifa',
      'notifications_subtitle': 'Dhibiti arifa za programu',
      'language': 'Lugha',
      'language_subtitle': 'Chagua lugha ya programu',
      'security': 'Usalama',
      'security_subtitle': 'Mipangilio ya usalama',
      'backup': 'Hifadhi',
      'backup_subtitle': 'Hifadhi na rejesha data',
      'about_app': 'Kuhusu Programu',
      'about_app_subtitle': 'Maelezo ya programu',
      'help': 'Msaada',
      'help_subtitle': 'Pata msaada wa kutumia programu',
      'logout_confirm': 'Je, una uhakika unataka kutoka?',
      'version': 'Toleo',
      'app_description': 'Programu ya kusimamia biashara za pikipiki',
      'copyright': '© 2024 All in One',

      // Debts/Payments common (fallback via translate() will prettify missing keys)

      // Users management
      'users': 'Watumiaji',
      'users_subtitle': 'Dhibiti watumiaji wa programu',
      'users_management': 'Usimamizi wa Watumiaji',
      'create_user': 'Tengeneza Mtumiaji',
      'full_name': 'Jina Kamili',
      'role': 'Jukumu',
      'active': 'Hai',
      'expiring': 'Inayoisha',
      'expired': 'Imeisha',
      'reset_password': 'Rejesha Nywila',
      'user_created_successfully': 'Mtumiaji ameundwa kikamilifu',
      'password_reset_successfully': 'Nywila imerejeshwa kikamilifu',
      'default_password_note':
          'Nywila chaguomsingi itakuwa jina la mwisho (surname) kwa HERUFI KUBWA. Mfano: Samwel Mahenye Magaiwa => "MAGAIWA".',

      // Language Selection
      'select_language': 'Chagua Lugha',
      'english': 'Kiingereza',
      'swahili': 'Kiswahili',
      'language_changed': 'Lugha imebadilishwa kikamilifu',

      // Notifications Settings
      'push_notifications': 'Arifa za Kusukuma',
      'email_notifications': 'Arifa za Barua pepe',
      'payment_alerts': 'Arifa za Malipo',
      'debt_reminders': 'Mikumbuzo ya Madeni',
      'system_updates': 'Masasisho ya Mfumo',

      // Security Settings
      'change_password': 'Badilisha Neno la Siri',
      'two_factor_auth': 'Uthibitisho wa Hatua Mbili',
      'login_history': 'Historia ya Kuingia',
      'current_password': 'Neno la Siri la Sasa',
      'new_password': 'Neno la Siri Jipya',
      'confirm_password': 'Thibitisha Neno la Siri',
      'password_changed': 'Neno la siri limebadilishwa kikamilifu',
      'two_factor_enabled_msg': 'Uthibitisho wa hatua mbili umewezeshwa',
      'two_factor_disabled_msg': 'Uthibitisho wa hatua mbili umelemazwa',
      'no_login_history': 'Hakuna historia ya kuingia kupatikana.',
      'failed_to_update': 'Imeshindikana kusasisha',

      // Backup Settings
      'auto_backup': 'Hifadhi Otomatiki',
      'backup_now': 'Hifadhi Sasa',
      'restore_data': 'Rejesha Data',
      'last_backup': 'Hifadhi ya Mwisho',
      'backup_successful': 'Hifadhi imekamilika kikamilifu',
      'restore_successful': 'Data imerejeshwa kikamilifu',

      // Dashboard
      'daily_revenue': 'Mapato ya Siku',
      'weekly_revenue': 'Mapato ya Wiki',
      'monthly_revenue': 'Mapato ya Mwezi',
      'total_revenue': 'Jumla ya Mapato',
      'drivers': 'Madereva',

      // Receipts details/viewer additions
      'receipt_details': 'Maelezo ya Risiti',
      'receipt': 'Risiti',
      'receipt_number': 'Namba ya Risiti',
      'payment_id': 'ID ya Malipo',
      // Receipt status labels
      'receipt_status_generated': 'Imetengenezwa',
      'receipt_status_sent': 'Imetumwa',
      'receipt_status_cancelled': 'Imeghairiwa',
      'receipt_status_pending': 'Zinazosubiri',
      'generated_date': 'Tarehe ya Kutengeneza',
      'payment_period': 'Muda Uliolipwa',
      'debt_on_dates': 'Deni la Tarehe',
      'step_1_generate_receipt': 'Hatua ya 1: Tengeneza Risiti',
      'press_below_to_generate_receipt':
          'Bonyeza hapa chini kutengeneza risiti ya malipo haya.',
      'receipt_generated_you_can_send':
          'Risiti imetengenezwa. Unaweza kuituma sasa.',
      'already_generated': 'Tayari Imetengenezwa',
      'generating': 'Inatengeneza...',
      'receipt_generated': 'Risiti imetengenezwa!',
      'receipt_already_generated_for_payment':
          'Risiti tayari imetengenezwa kwa malipo haya!',
      'failed_to_generate_receipt': 'Imeshindikana kutengeneza risiti',
      'step_2_send_receipt': 'Hatua ya 2: Tuma Risiti',
      'recipient_email': 'Barua Pepe ya Mpokeaji',
      'recipient_phone': 'Namba ya Simu ya WhatsApp/SMS',
      'sending': 'Inatuma...',
      'sent': 'Imetumwa',
      'send_receipt': 'Tuma Risiti',
      'after_sending_status_will_change':
          'Baada ya kutuma, hali ya muamala itabadilika kuwa “risiti imetolewa.”',
      'missing_receipt_id': 'Hakuna kitambulisho cha risiti',
      'enter_contact_info': 'Weka mawasiliano (namba au barua pepe)',
      'receipt_sent': 'Risiti imetumwa!',
      'failed_to_send_receipt': 'Imeshindikana kutuma risiti',
      'total_payment': 'Jumla ya Malipo',
      'trips': 'Safari (Trips)',
      'outstanding_info_message':
          'Maelezo ya deni yaliyosalia yatajumlishwa kwenye ujumbe wa risiti utakapotumwa.',
      'send_info': 'Maelezo ya Kutuma',
      'sent_date': 'Tarehe ya Kutuma',
      'sent_to': 'Imetumwa kwa',
      'resend_receipt': 'Tuma Tena Risiti',
      'phone_or_email': 'Namba ya Simu au Barua Pepe',
      'phone_or_email_required': 'Weka namba ya simu au barua pepe',
      'send_again': 'Tuma Tena',
      'receipt_resent': 'Risiti imetumwa tena!',

      // Payments (record payment flow)
      'record_payment': 'Rekodi Malipo',
      'record_payment_subtitle': 'Chagua dereva kisha rekodi malipo yake',
      'select_payment_days': 'Chagua Siku za Malipo',
      'driver_has_no_debt': 'Dereva huyu hana deni lolote',
      'vehicles': 'Vyombo vya Usafiri',
      'receipts_generated': 'Malipo Yenye Risiti',
      'pending_receipts': 'Yamelipwa Bado Risiti',
      'unpaid_debts': 'Malipo Yasiyolipwa',

      // Receipts
      'receipts': 'Risiti',
      'generate_receipt': 'Tengeneza Risiti',
      'pending': 'Zinazosubiri',
      'all': 'Zote',
      'receipt_management': 'Uongozi wa Risiti',
      'generate_and_send_receipts': 'Tengeneza na tuma risiti kwa madereva',
      'no_pending_receipts': 'Hakuna malipo yanayosubiri risiti',
      'no_receipts_generated': 'Hakuna risiti zilizozalishwa',
      'receipts_list_empty': 'Utaona orodha ya risiti zote hapa',
      'all_payments_have_receipts': 'Malipo yote yamesha tengenezwa risiti',

      // Vichujio na muhtasari wa madeni (transport)
      'filter_unpaid_only': 'Bila Kulipwa',
      'filter_paid_only': 'Yaliyolipwa',
      'summary_total_debt': 'Jumla ya Deni',
      'summary_unpaid_days': 'Siku zisizolipwa',
      'last_payment': 'Malipo ya mwisho',
      'paid_total': 'Jumla iliyolipwa',
      'unpaid_total': 'Jumla isiyolipwa',

      // Common Buttons/Actions
      'view_details': 'Ona Maelezo',
      'view_all': 'Ona Zote',
      'add_new': 'Ongeza Mpya',
      'search': 'Tafuta',
      'filter': 'Chuja',
      'export': 'Hamisha',
      'import': 'Ingiza',
      'print': 'Chapisha',
      'share': 'Shiriki',
      'send': 'Tuma',

      // Dashboard card menu items and actions (Swahili)
      'drivers_who_paid': 'Madereva Waliolipa',
      'revenue_breakdown': 'Muhtasari wa Mapato',
      'export_data': 'Hamisha Data',
      'import_data': 'Ingiza Data',
      'current_value': 'Thamani ya sasa',
      'close': 'Funga',
      'process_pending_receipts': 'Chakata Risiti Zinazosubiri',
      'confirm_process_pending_receipts':
          'Je, unataka kuchakata risiti zote zinazosubiri?',
      'process': 'Chakata',
      'pending_receipts_processed': 'Risiti zilizosubiri zimechakata',
      'send_payment_reminders': 'Tuma Vikumbusho vya Malipo',
      'send_reminders': 'Tuma Vikumbusho',
      'confirm_send_reminders': 'Tuma vikumbusho kwa waliokosa kulipa?',
      'payment_reminders_sent': 'Vikumbusho vimetumwa',
      'confirm_export_data': 'Thibitisha uhamishaji wa data kwa',
      'data_exported_successfully': 'Data imehamishwa kikamilifu',
      'menu': 'Menyu',
      'active_drivers_only': 'Madereva Hai Pekee',
      'all_vehicles': 'Magari Yote',
      'active_vehicles_only': 'Magari Yanayotumika Pekee',
      'all_receipts': 'Risiti Zote',
      'manage_vehicles': 'Simamia Magari',

      // Extra dashboard titles/descriptions used by cards
      'payments_with_receipts': 'Malipo yenye Risiti',
      'payments_with_receipts_desc':
          'Idadi ya malipo ambayo tayari yana risiti.',
      'paid_awaiting_receipts': 'Yamelipwa Bado Risiti',
      'paid_awaiting_receipts_desc':
          'Malipo yaliyolipwa yakisubiri risiti kutengenezwa.',
      'unpaid_payments': 'Malipo Yasiyolipwa',
      'unpaid_payments_desc': 'Malipo ambayo bado hayajalipwa.',
      'daily_revenue_desc': 'Mapato yaliyokusanywa leo.',
      'weekly_revenue_desc': 'Mapato ya wiki hii.',
      'monthly_revenue_desc': 'Mapato ya mwezi huu.',
      'drivers_desc': 'Idadi ya madereva waliosajiliwa.',
      'vehicles_desc': 'Idadi ya magari yaliyosajiliwa.',
      'additional_card_info': 'Maelezo ya ziada.',

      // Navigation Drawer (additional entries)
      'payments': 'Malipo',
      'debt_records': 'Rekodi Madeni',
      'analytics': 'Takwimu',
      'reports': 'Ripoti',
      'reminders': 'Mikumbuzo',
      'communications': 'Mawasiliano',
      // Communications
      'communications_title': 'Mawasiliano',
      'communications_summary_title': 'Muhtasari wa Mawasiliano',
      'filter_communications': 'Chuja Mawasiliano',
      'search_driver_content': 'Tafuta dereva au ujumbe...',
      'add': 'Ongeza',
      'add_communication': 'Ongeza Mawasiliano',
      'type': 'Aina',
      'status': 'Hali',
      'call': 'Simu',
      'note': 'Kumbuka',
      'answered': 'Yamejibiwa',
      'unanswered': 'Hayajajibiwa',
      'total_communications': 'Mawasiliano Yote',
      'recent_7_days': 'Siku 7 Zilizopita',
      'response_rate': 'Kiwango cha Majibu',
      'loading_dashboard': 'Inapakia Dashboard...',
      // Driver dashboard common labels (Swahili)
      'driver_payment_stats': 'Takwimu za Malipo',
      'quick_actions': 'Vitendo vya Haraka',
      'payment_history': 'Historia ya Malipo',
      'today': 'Leo',
      'week': 'Wiki',
      'month': 'Mwezi',
      'your_vehicle': 'Gari Lako',
      'plate_number': 'Nambari',
      'status_active': 'Inatumika',
      'status_completed': 'Imekamilika',
      'status_cancelled': 'Imeghairiwa',
      'status_expired': 'Imeisha',
      // Welcome and reminders
      'welcome': 'Karibu',
      // Agreement labels
      'agreement_total_title': 'Jumla ya Kukamilisha Mkataba',
      'agreement_total_subtitle':
          'Kiasi kinachotakiwa kulipwa kulingana na mkataba',
      'agreement_daily_title': 'Kiasi cha Dei Waka',
      'agreement_daily_subtitle':
          'Kiasi cha kulipa kwa makubaliano ya Dei Waka',
      // Driver pages
      'my_receipts': 'Risiti Zangu',
      'no_receipts': 'Hakuna risiti',
      'no_reminders': 'Hakuna vikumbusho',
      'try_again': 'Jaribu Tena',
      'amount': 'Kiasi',
      'driver': 'Dereva',
      'vehicle': 'Gari',
      'date': 'Tarehe',
      'covered_days': 'Siku Zilizolipwa',
      'remarks': 'Maelezo',
      'payment': 'Malipo',
      'debt_clearance': 'Kulipa Deni',
      'days': 'Siku',
      'no_debt': 'Hakuna deni',
      'has_debt': 'Bado una deni',
      'total_debt_label': 'Jumla ya deni',
      // Reminders/Debts (driver)
      'outstanding_debts': 'Madeni Yaliyosalia',
      'total_outstanding': 'Jumla ya Deni',
      'due_date': 'Tarehe ya Kulipa',
      'days_overdue': 'Siku za Kudaiwa',

      // Drivers Management Screen
      'drivers_management': 'Usimamizi wa Madereva',
      'add_driver': 'Ongeza Dereva',
      'driver_name': 'Jina la Dereva',
      'driver_phone': 'Nambari ya Simu',
      'driver_email': 'Anwani ya Barua Pepe',
      'driver_license': 'Nambari ya Leseni',
      'driver_status': 'Hali',
      'active_driver': 'Hai',
      'inactive_driver': 'Hahai',
      'edit_driver': 'Hariri Dereva',
      'delete_driver': 'Futa Dereva',
      'driver_details': 'Maelezo ya Dereva',
      'total_drivers': 'Madereva Wote',
      'active_drivers': 'Madereva Hai',
      'driver_added_successfully': 'Dereva ameongezwa kikamilifu',
      'driver_updated_successfully': 'Dereva amebadilishwa kikamilifu',
      'driver_deleted_successfully': 'Dereva amefutwa kikamilifu',
      'confirm_delete_driver': 'Je, una uhakika unataka kumfuta dereva huyu?',
      'no_drivers_found': 'Hakuna madereva waliopatikana',
      'search_drivers': 'Tafuta madereva...',

      // Vehicles Management Screen
      'vehicles_management': 'Usimamizi wa Vyombo vya Usafiri',
      'add_vehicle': 'Ongeza Gari',
      'vehicle_plate': 'Nambari ya Gari',
      'vehicle_model': 'Aina ya Gari',
      'vehicle_year': 'Mwaka',
      'vehicle_type': 'Aina ya Chombo',
      'vehicle_status': 'Hali',
      'active_vehicle': 'Hai',
      'inactive_vehicle': 'Hahai',
      'edit_vehicle': 'Hariri Gari',
      'delete_vehicle': 'Futa Gari',
      'vehicle_details': 'Maelezo ya Gari',
      'total_vehicles': 'Magari Yote',
      'active_vehicles': 'Magari Yanayotumika',
      'vehicle_added_successfully': 'Gari limeongezwa kikamilifu',
      'vehicle_updated_successfully': 'Gari limebadilishwa kikamilifu',
      'vehicle_deleted_successfully': 'Gari limefutwa kikamilifu',
      'confirm_delete_vehicle': 'Je, una uhakika unataka kufuta gari hili?',
      'no_vehicles_found': 'Hakuna magari yaliyopatikana',
      'search_vehicles': 'Tafuta magari...',

      // Payments Screen
      'payments_management': 'Usimamizi wa Malipo',
      'payment_amount': 'Kiasi',
      'payment_date': 'Tarehe ya Malipo',
      'payment_method': 'Njia ya Malipo',
      'payment_status': 'Hali',
      'payment_reference': 'Nambari ya Kumbukumbu',
      'payment_driver': 'Dereva',
      'payment_vehicle': 'Gari',
      'add_payment': 'Ongeza Malipo',
      'edit_payment': 'Hariri Malipo',
      'delete_payment': 'Futa Malipo',
      'payment_details': 'Maelezo ya Malipo',
      'total_payments': 'Malipo Yote',
      'paid_payments': 'Yamelipwa',
      'pending_payments': 'Yanasubiri',
      'payment_added_successfully': 'Malipo yameongezwa kikamilifu',
      'payment_updated_successfully': 'Malipo yamebadilishwa kikamilifu',
      'payment_deleted_successfully': 'Malipo yamefutwa kikamilifu',
      'confirm_delete_payment': 'Je, una uhakika unataka kufuta malipo haya?',
      'no_payments_found': 'Hakuna malipo yaliyopatikana',
      'search_payments': 'Tafuta malipo...',
      'cash': 'Fedha Taslimu',
      'mobile_money': 'Pesa za Simu',
      'bank_transfer': 'Uhamisho wa Benki',
      'paid': 'Yamelipwa',
      'overdue': 'Yamechelewa',

      // Debts Management Screen
      'debts_management': 'Usimamizi wa Madeni',
      'debt_amount': 'Kiasi cha Deni',
      'debt_date': 'Tarehe ya Deni',
      'debt_due_date': 'Tarehe ya Mwisho',
      'debt_status': 'Hali',
      'debt_driver': 'Dereva',
      'debt_description': 'Maelezo',
      'add_debt': 'Ongeza Deni',
      'edit_debt': 'Hariri Deni',
      'delete_debt': 'Futa Deni',
      'debt_details': 'Maelezo ya Deni',
      'total_debts': 'Madeni Yote',
      'paid_debts': 'Madeni Yaliyolipwa',
      'debt_added_successfully': 'Deni limeongezwa kikamilifu',
      'debt_updated_successfully': 'Deni limebadilishwa kikamilifu',
      'debt_deleted_successfully': 'Deni limefutwa kikamilifu',
      'confirm_delete_debt': 'Je, una uhakika unataka kufuta deni hili?',
      'no_debts_found': 'Hakuna madeni yaliyopatikana',
      'search_debts': 'Tafuta madeni...',
      'mark_as_paid': 'Weka kama Yamelipwa',
      'mark_as_unpaid': 'Weka kama Hayajalipwa',

      // Analytics Screen
      'analytics_dashboard': 'Dashibodi ya Takwimu',
      'revenue_analytics': 'Takwimu za Mapato',
      'driver_analytics': 'Takwimu za Madereva',
      'vehicle_analytics': 'Takwimu za Magari',
      'payment_analytics': 'Takwimu za Malipo',
      'performance_metrics': 'Vipimo vya Utendaji',
      'revenue_trends': 'Mwelekeo wa Mapato',
      'top_drivers': 'Madereva Bora',
      'active_vehicles_chart': 'Magari Yanayotumika',
      'monthly_comparison': 'Ulinganishi wa Mwezi',
      'yearly_comparison': 'Ulinganishi wa Mwaka',
      'export_analytics': 'Hamisha Takwimu',
      'date_range': 'Kipindi cha Tarehe',
      'from_date': 'Kutoka Tarehe',
      'to_date': 'Hadi Tarehe',
      'apply_filter': 'Tumia Kichuja',
      'clear_filter': 'Futa Kichuja',

      // Reports Screen
      'reports_dashboard': 'Dashibodi ya Ripoti',
      'generate_report': 'Tengeneza Ripoti',
      'driver_report': 'Ripoti ya Madereva',
      'vehicle_report': 'Ripoti ya Magari',
      'payment_report': 'Ripoti ya Malipo',
      'debt_report': 'Ripoti ya Madeni',
      'revenue_report': 'Ripoti ya Mapato',
      'monthly_report': 'Ripoti ya Mwezi',
      'yearly_report': 'Ripoti ya Mwaka',
      'custom_report': 'Ripoti Maalum',
      'report_type': 'Aina ya Ripoti',
      'report_period': 'Kipindi cha Ripoti',
      'report_format': 'Muundo wa Ripoti',
      'pdf_format': 'PDF',
      'excel_format': 'Excel',
      'csv_format': 'CSV',
      'download_report': 'Pakua Ripoti',
      'email_report': 'Tuma Ripoti kwa Barua Pepe',
      'report_generated_successfully': 'Ripoti imetengenezwa kikamilifu',
      'report_generation_failed': 'Kutengeneza ripoti kumeshindikana',

      // Reminders Screen
      'reminders_management': 'Usimamizi wa Mikumbuzo',
      'add_reminder': 'Ongeza Ukumbusho',
      'reminder_title': 'Kichwa cha Ukumbusho',
      'reminder_message': 'Ujumbe',
      'reminder_date': 'Tarehe ya Ukumbusho',
      'reminder_time': 'Muda wa Ukumbusho',
      'reminder_type': 'Aina',
      'payment_reminder': 'Ukumbusho wa Malipo',
      'maintenance_reminder': 'Ukumbusho wa Matengenezo',
      'general_reminder': 'Ukumbusho wa Jumla',
      'reminder_status': 'Hali',
      'active_reminder': 'Hai',
      'completed_reminder': 'Umekamilika',
      'edit_reminder': 'Hariri Ukumbusho',
      'delete_reminder': 'Futa Ukumbusho',
      'reminder_details': 'Maelezo ya Ukumbusho',
      'total_reminders': 'Mikumbuzo Yote',
      'active_reminders': 'Mikumbuzo Hai',
      'completed_reminders': 'Zilizokamilika',
      'reminder_added_successfully': 'Ukumbusho umeongezwa kikamilifu',
      'reminder_updated_successfully': 'Ukumbusho umebadilishwa kikamilifu',
      'reminder_deleted_successfully': 'Ukumbusho umefutwa kikamilifu',
      'confirm_delete_reminder':
          'Je, una uhakika unataka kufuta ukumbusho huu?',
      'no_reminders_found': 'Hakuna mikumbuzo iliyopatikana',
      'search_reminders': 'Tafuta mikumbuzo...',
      'mark_as_completed': 'Weka kama Umekamilika',
      'send_reminder': 'Tuma Ukumbusho',

      // Communications Screen
      'communications_management': 'Mawasiliano',
      'send_message': 'Tuma Ujumbe',
      'message_title': 'Kichwa cha Ujumbe',
      'message_content': 'Maudhui ya Ujumbe',
      'message_recipients': 'Wapokeaji',
      'all_drivers': 'Madereva Wote',
      'selected_drivers': 'Madereva Waliochaguliwa',
      'message_type': 'Aina ya Ujumbe',
      'sms_message': 'SMS',
      'email_message': 'Barua Pepe',
      'push_notification': 'Arifa ya Kusukuma',
      'send_immediately': 'Tuma Mara Moja',
      'schedule_message': 'Ratibisha Ujumbe',
      'scheduled_date': 'Tarehe Iliyoratibishwa',
      'scheduled_time': 'Muda Ulioratibishwa',
      'message_history': 'Historia ya Ujumbe',
      'sent_messages': 'Ujumbe Uliotumwa',
      'scheduled_messages': 'Ujumbe Ulioratibishwa',
      'message_status': 'Hali',
      'message_sent': 'Umetumwa',
      'message_scheduled': 'Umeratibishwa',
      'message_failed': 'Umeshindikana',
      'message_delivered': 'Umefika',
      'message_sent_successfully': 'Ujumbe umetumwa kikamilifu',
      'message_scheduled_successfully': 'Ujumbe umeratibishwa kikamilifu',
      'message_failed_to_send': 'Kutuma ujumbe kumeshindikana',
      'no_messages_found': 'Hakuna ujumbe uliopatikana',
      'search_messages': 'Tafuta ujumbe...',
      'select_recipients': 'Chagua Wapokeaji',

      // Login Screen
      'login_successful': 'Umeingia kikamilifu!',
      'login_failed': 'Kuingia kumeshindikana',
      'login_error': 'Hitilafu katika kuingia: ',
      'demo_credentials_filled': 'Taarifa za demo zimejazwa',
      'database_credentials_filled': 'Taarifa za database zimejazwa',
      'forgot_password': 'Umesahau Nywila?',
      'forgot_password_message':
          'Kipengele cha kurudisha nywila kinatengenezwa. Kwa sasa, tumia taarifa za demo au wasiliana na msimamizi.',
      'use_database': 'Tumia Database',
      'email': 'Barua pepe',
      'password': 'Neno la siri',
      'phone_number': 'Nambari ya simu',
      'signin': 'Ingia',
      'welcome_back': 'Karibu Tena',
      'signin_subtitle': 'Ingia ili kuendelea kwenye akaunti yako',

      // Uchaguzi wa huduma
      'select_service': 'Chagua Huduma',
      'select_service_subtitle': 'Chagua unachotaka kusimamia leo',
      'inventory_service': 'Hesabu (Inventory)',
      'rental_service': 'All in One',
      'transport_service': 'Usafirishaji (Transport)',
      'coming_soon': 'Inakuja hivi karibuni…',
      'switch_service': 'Badili Huduma',
      // Moduli ya Hesabu
      'inventory_dashboard': 'Dashibodi ya Hesabu',
      'products': 'Bidhaa',
      'stock_levels': 'Viwango vya Stoo',
      'stock_in_out_transfer': 'Ingizo/Mauzo/Uhamisho',
      'stock_in': 'Ingiza Stoo',
      'stock_out': 'Toa Stoo',
      'stock_transfer': 'Hamisha',
      'sales': 'Mauzo',
      'total_sales_today': 'Mauzo ya Leo',
      'profit_today': 'Faida (Leo)',
      'profit_week': 'Faida (Wiki)',
      'profit_month': 'Faida (Mwezi)',
      'sales_trend': 'Mwelekeo wa Mauzo',
      'low_stock': 'Stoo Chache',
      'quantity': 'Kiasi',
      'min_stock': 'Kiwango cha Chini',
      'warehouse': 'Ghala',
      'sku': 'SKU',
      'product': 'Bidhaa',
      'reference': 'Marejeo',
      'from_warehouse': 'Kutoka Ghala',
      'to_warehouse': 'Kwenda Ghala',
      'saved': 'Imehifadhiwa',
      'add_product': 'Ongeza Bidhaa',
      'search_products': 'Tafuta bidhaa…',
      'create_sale_pos': 'Tengeneza Mauzo (POS)',
      'create_sale_hint': 'Ongeza bidhaa, weka kiasi, chagua aina ya malipo.',
      'add_products': 'Ongeza Bidhaa',
      'checkout': 'Kamilisha Malipo',
      'recent_sales': 'Mauzo ya Hivi Karibuni',
      'items': 'vipengee',
      'payment_due': 'Malipo Yanatakiwa',
      'payment_due_desc': 'Malipo yanakaribia kuhitajika.',
      'low_stock_desc': 'Kiwango cha stoo kimezidi kuwa chini ya kiwango.',
      'mark_done': 'Weka Kamilika',
      'snooze': 'Sogeza Muda',
      'open': 'Wazi',
      'snoozed': 'Imeahirishwa',
      'done': 'Imekamilika',

      // POS / Mauzo
      'payment_mode': 'Aina ya Malipo',
      'debt': 'Deni',
      'partial': 'Sehemu (Partial)',
      'customer': 'Mteja',
      'customer_required': 'Mteja anahitajika kwa Deni/Partial',
      'add_to_cart': 'Ongeza Kwenye Kikapu',
      'qty': 'Idadi',
      'unit_price': 'Bei kwa Kimoja',
      'subtotal': 'Jumla Ndogo',
      'total': 'Jumla',
      'profit': 'Faida',
      'paid_amount': 'Kiasi Kilicholipwa',
      'select_customer': 'Chagua mteja',
      'cannot_negative_stock': 'Shughuli itasababisha stoo hasi',
      'balance': 'Baki',
      'add_customer': 'Ongeza Mteja',
      'customer_name': 'Jina la Mteja',
      'address': 'Anwani',

      // Rental navigation
      'rental_dashboard': 'Dashibodi ya Upangaji',
      'tenants': 'Wapangaji',
      'properties': 'Majengo/Nyumba',
      'rent_payments': 'Malipo ya Kodi',
      'arrears': 'Madeni ya Kodi',
      'billing_reports': 'Ripoti za Ankara',
      'sms_history': 'Historia ya SMS',
      'lease_agreements': 'Mikataba ya Kukodi',
      'lease_templates': 'Sampuli za Mikataba',
      'tenant_self_service': 'Akaunti Yangu',
      'helpdesk': 'Helpdesk',
      'helpdesk_subtitle': 'Angalia miongozo na wasiliana nasi',

      // Rental Onboarding (Swahili)
      'register_tenant': 'Sajili Mpangaji',
      'step': 'Hatua',
      'personal_info': 'Taarifa Binafsi',
      'emergency_contact': 'Mawasiliano ya Dharura',
      'identification': 'Utambulisho',
      'employment': 'Ajira',
      'history': 'Historia ya Upangaji',
      'peeps': 'Wakazi & Wanyama',
      'terms': 'Vigezo & Nyumba',
      'contact_identity': 'Mawasiliano na Kitambulisho',
      'employment_history': 'Kazi na Historia',
      'living_property': 'Maisha na Jengo',
      'media': 'Picha/Vyombo',
      'terms_conditions': 'Vigezo na Masharti',
      'first_name': 'Jina la Kwanza',
      'last_name': 'Jina la Mwisho',
      'gender': 'Jinsia',
      'male': 'Mwanaume',
      'female': 'Mwanamke',
      'birth_date': 'Tarehe ya Kuzaliwa',
      'nida_id': 'Namba ya NIDA',
      'phone_no': 'Namba ya Simu',
      'email_address': 'Barua Pepe',
      'contact_name': 'Jina la Mawasiliano',
      'relationship': 'Uhusiano',
      'id_number': 'Namba ya Kitambulisho',
      'state_issued': 'Mkoa Uliotoa',
      'exp_date': 'Tarehe ya Kuisha',
      'upload_id': 'Pakia Kitambulisho',
      'employer': 'Mwajiri',
      'job_title': 'Jukumu la Kazi',
      'employment_duration': 'Muda wa Kazi',
      'work_no': 'Simu ya Kazini',
      'currently_employed': 'Nimeajiriwa kwa Sasa',
      'prev_address': 'Anwani ya Zamani',
      'stay_duration': 'Muda wa Kukaa',
      'reason_leaving': 'Sababu ya Kuhama',
      'landlord_name': 'Jina la Mwenye Nyumba',
      'landlord_phone': 'Simu ya Mwenye Nyumba',
      'adults_count': 'Watu Wazima',
      'children_count': 'Watoto',
      'others_live_here': 'Je, kuna wengine wataishi?',
      'pet_type': 'Aina ya Mnyama',
      'breed': 'Urefu/Aina',
      'pet_age': 'Umri wa Mnyama',
      'pet_weight': 'Uzito',
      'others_stay': 'Wengine watakaa?',
      'additional_notes': 'Maelezo zaidi',
      'select_property': 'Chagua Jengo',
      'select_house': 'Chagua Nyumba/Chumba',
      'start_date': 'Tarehe ya Kuanza',
      'rent_amount': 'Kodi',
      'deposit_amount': 'Amana',
      'deposit': 'Amana (Deposit)',
      'deposit_exceeds_rent': 'Amana haiwezi kuzidi kodi',
      'capture_tenant_photo': 'Piga Picha ya Mpangaji',
      'photo_attached': 'Picha imepakiwa kikamilifu',
      'tap_to_upload': 'Gusa kupakia picha',
      'accept_terms': 'Ninakubali Vigezo na Masharti',
      'agree_privacy': 'Ninakubali Sera ya Faragha',
      'previous': 'Nyuma',
      'next_step': 'Hatua Inayofuata',
      'submit': 'Wasilisha',
      'tenant_onboarded_success': 'Mpangaji amesajiliwa kikamilifu!',
      'coming_soon_arrears': 'Ufuatiliaji wa Madeni Unakuja Hivi Karibuni',
      'coming_soon_tenants': 'Orodha ya Wapangaji Inakuja Hivi Karibuni',
      'coming_soon_receipts': 'Risiti za Kodi Zinakuja Hivi Karibuni',
      'failed_to_onboard': 'Imeshindikana kusajili. Jaribu tena.',
      'select_house_error': 'Tafadhali chagua nyumba katika Hatua ya 7',
      'accept_terms_error': 'Tafadhali kubali Vigezo na Sera ya Faragha',
      'loading_properties': 'Inapakia majengo...',
      'no_properties_found': 'Hakuna majengo yaliyopatikana',
      'houses': 'Nyumba',
      'occupancy': 'Ukaazi',
      'welcome_landlord': 'Karibu, Mwenye Nyumba',
      'add_property': 'Ongeza Jengo',
      'view_bills': 'Angalia Ankara',
      'onboard_tenant': 'Sajili Mpangaji',
      'my_properties': 'Majengo Yangu',
      'see_all': 'Ona Zote',
      'rent_billing': 'Ankara za Kodi',
      'no_bills_found': 'Hakuna ankara zilizopatikana',
      'unpaid': 'Hazijalipwa',
      'due': 'Mwisho',
      'tap_to_pay': 'Gusa Kulipa',
      'amount_paid_tsh': 'Kiasi Kilicholipwa (Tsh)',
      'confirm_payment': 'Thibitisha Malipo',
      'recording_payment_for': 'Kurekodi malipo ya',
      'payment_success': 'Malipo yamehifadhiwa!',
      'payment_failed': 'Imeshindikana kuhifadhi malipo.',
      'digital_receipt': 'Risiti ya Kidijitali',
      'payment_successful': 'Malipo Yamefanikiwa',
      'receipt_prefix': 'Risiti #',
      'sharing_success': 'Risiti imeshirikiwa kikamilifu!',
      'printing_msg': 'Inatuma kwenye printa...',
      'thank_you_payment': 'Asante kwa malipo yako!',
      'mapato_rental_service': 'Huduma ya All In One',
      'maintenance_end_date': 'Tarehe ya Kukamilisha',
      'available_from': 'Itapatikana kuanzia',
      'under_maintenance': 'Kwenye Matengenezo',

      // Rental Property Management
      'property_details': 'Maelezo ya Jengo',
      'edit_property': 'Hariri Jengo',
      'maintenance': 'Matengenezo',
      'no_properties': 'Bado hakuna majengo',
      'add_property_hint': 'Anza kwa kuongeza jengo lako la kwanza.',
      'occupied': 'Yamepangwa',
      'vacant': 'Wazi',
      'basic_information': 'Habari za Msingi',
      'property_name': 'Jina la Jengo',
      'property_type': 'Aina ya Jengo',
      'configuration': 'Mipangilio',
      'billing_cycle': 'Muda wa Malipo',
      'property_created': 'Jengo limeundwa kikamilifu!',
      'property_updated': 'Jengo limesasishwa kikamilifu!',
      'field_required': 'Sehemu hii inahitajika',
      'total_houses': 'Jumla ya Nyumba',
      'blocks': 'Vitalu',
      'recent_payments': 'Malipo ya Hivi Karibuni',
      'no_payments': 'Hakuna malipo',
      'active_leases': 'Hadi Sasa',
      'expiring_leases': 'Inayoisha',
      'all_leases': 'Zote',
      'no_leases_found': 'Hakuna mikataba hapa',
      'house': 'Nyumba',
      'lease_wizard': 'Mkataba wa Upangaji',
      'step_selection': 'Uteuzi',
      'step_terms': 'Vipindi',
      'step_payments': 'Malipo',
      'step_utilities': 'Huduma',
      'step_rules': 'Sheria',
      'step_review': 'Uhakiki',
      'complete': 'Kamilisha',
      'rent_monthly': 'Kodi ya Mwezi',
      'security_deposit': 'Dhamana (Deposit)',
      'deposit_paid': 'Dhamana Aliyolipa',
      'advance_months': 'Miezi ya Mapema (Kodi)',
      'total_prepaid': 'Jumla ya Kodi ya Mapema',
      'paid_until': 'Imelipiwa Mpaka',
      'default_landlord_obligations':
          '1. Kudumisha nyumba katika hali ya kuishi.\n2. Kukarabati kasoro za msingi.\n3. Kuheshimu faragha ya mpangaji.',
      'default_tenant_obligations':
          '1. Kulipa kodi kwa wakati.\n2. Kuweka mazingira katika hali ya usafi.\n3. Kuepuka kelele zinazopitiliza.',
      'default_termination_policy':
          'Upande wowote unaweza kusitisha mkataba huu kwa kutoa notisi ya maandishi ya siku 30.',
      'due_day': 'Siku ya Kulipa',
      'grace_period': 'Siku za Mapumziko',
      'late_fee_type': 'Aina ya Penati',
      'auto_renew': 'Jiongeze Kiotomatiki',
      'house_details': 'Maelezo ya Nyumba',
      'tenant_obligations': 'Wajibu wa Mpangaji',
      'landlord_obligations': 'Wajibu wa Mwenye Nyumba',
      'termination_policy': 'Sera ya Kuvunja Mkataba',
      'review_lease': 'Hakiki Vipengele vya Mkataba',
      'utilities_water': 'Maji',
      'utilities_electricity': 'Umeme',
      'service_charge': 'Gharama za Huduma',
      'parking_space': 'Maegesho',
      'wizard_complete_msg':
          'Bonyeza "Kamilisha" ili kutengeneza mkataba huu rasmi.',
      'base_rent': 'Kodi ya Msingi',
      'base_deposit': 'Amana ya Msingi',
      'utility_billing': 'Bili za Huduma',
      'enabled': 'Imewezeshwa',
      'disabled': 'Haijawezeshwa',
      'gps_location': 'Mahali (GPS)',
      'ownership_details': 'Maelezo ya Umiliki',
      'floor': 'Ghorofa',
      'area_sqm': 'Eneo (sqm)',
      'notes': 'Maelezo',
      'confirm_delete_property': 'Futa Mali?',
      'confirm_delete_house': 'Futa Nyumba?',
      'cannot_be_undone': 'Hatua hii haiwezi kutenguliwa.',
      'property_delete_success': 'Mali imefutwa vizuri',
      'property_delete_failed': 'Imeshindikana kufuta mali',
      'house_delete_success': 'Nyumba imefutwa vizuri',
      'house_delete_failed': 'Imeshindikana kufuta nyumba',
      'unit_number': 'Namba ya Nyumba',
      'edit_house': 'Hariri Nyumba',
      'update': 'Sasisha',
      'signature_upload': 'Sahihi / Upakiaji wa Mkataba',
      'upload_signed_copy': 'Pakia Nakala Iliyosainiwa (PDF/Image)',
      'please_select_tenant_house': 'Tafadhali chagua mpangaji na nyumba',
      'lease_created_success': 'Mkataba umetengenezwa kwa mafanikio',
      'lease_creation_failed': 'Imeshindikana kutengeneza mkataba',
      'retry': 'Jaribu Tena',
      'change_image': 'Badilisha Picha',
      'gallery': 'Nyaraka (Gallery)',
      'camera': 'Piga Picha (Kamera)',
      'months_covered': 'Miezi Iliyolipiwa',
      'tenant': 'Mpangaji',
      'property': 'Pango',
      'amount_paid': 'Kiasi Kilicholipwa',

      // House Features
      'add_house': 'Ongeza Nyumba',
      'register_house': 'Sajili Nyumba',
      'basic_info': 'Taarifa za Msingi',
      'house_number': 'Namba ya Nyumba',
      'house_type': 'Aina',
      'house_status': 'Hali',
      'house_features': 'Sifa za Ndani',
      'units_section': 'Idadi ya Vyumba/Milango',
      'total_units_label': 'Idadi ya Vyumba',
      'unit': 'Chumba',
      'name_units_hint': 'Weka majina au namba za vyumba',
      'rent_whole_house': 'Anapanga Nyumba Nzima?',
      'select_units_prompt': 'Chagua vyumba anavyopanga',
      'unit_rented': 'Chumba Kilichopangiwa',
      'has_fence': 'Ina Ukuta/Fence?',
      'has_tiles': 'Ina Tiles Chini?',
      'has_master_bedroom': 'Ina Master Bedroom?',
      'has_sitting_room': 'Ina Sebule?',
      'has_kitchen': 'Ina Jiko?',
      'kitchen_location': 'Jiko Lilipo',
      'inside': 'Ndani',
      'outside': 'Nje',
      'distance_from_road': 'Umbali Kutoka Barabara Kuu',
      'utilities_section': 'Huduma (Maji & Umeme)',
      'electricity_meter': 'Namba ya Mita ya Umeme',
      'electricity_type': 'Umeme',
      'water_meter': 'Namba ya Mita ya Maji',
      'water_type': 'Maji',
      'independent': 'Binafsi',
      'shared': 'Shiriki',
      'sharing_count': 'Watu Wangapi?',
      'landlord_lives_here': 'Mwenye Nyumba Anaishi Hapa?',
      'residence_ownership': 'Makazi & Umiliki',
      'photos_section': 'Picha za Nyumba & 3D',
      'photos_hint': 'Chukua au pakia picha kuonesha uzuri wa makazi.',
      'photos_required': 'Angalau picha 1 inahitajika (juu ya 5).',
      'add_photos': 'Ongeza Picha',
      'save_house': 'Hifadhi Nyumba',
      'update_house': 'Sasisha Nyumba',
      'invalid_amount': 'Kiasi si sahihi',
      'find_dream_home': 'Tafuta Makazi ya Ndoto Yako',
      'explore_houses_hint':
          'Vinjari na upate nyumba bora kulingana na mahitaji yako.',
      'search_houses': 'Tafuta nyumba, maeneo...',
      'no_houses_available': 'Hakuna nyumba zinazopatikana.',
      'from_road': 'Kutoka barabarani',
      'bedrooms': 'Vyumba',
      'bathrooms': 'Vyoo',
      'room': 'Chumba',
      'apartment': 'Apartment',
      'studio': 'Studio',
      'one_bedroom': 'Chumba 1',
      'two_bedroom': 'Vyumba 2',
      'bedsitter': 'Bedsitter',
      'login_to_manage': 'Ingia Kusimamia',
      'filters': 'Vichujio',
      'reset': 'Anza upya',
      'rooms': 'Vyumba',
      'landlord_status_on': 'Mwenye nyumba anaishi hapa',
      'landlord_status_off': 'Mwenye nyumba haishi hapa',
      'apply_filters': 'Tumia Vichujio',
      'image_name': 'Ipe Picha Jina',
      'image_name_hint': 'mf. Mbele ya Nyumba, Jiko, Bafu...',
      'photo': 'Picha',

      // Location Hierarchy
      'country': 'Nchi',
      'region': 'Mkoa',
      'district': 'Wilaya',
      'ward': 'Kata',
      'street': 'Mtaa / Kijiji',
      'place': 'Kitongoji',
      'location': 'Mahali',
      'select_country': 'Chagua Nchi',
      'select_region': 'Chagua Mkoa',
      'select_district': 'Chagua Wilaya',
      'select_ward': 'Chagua Kata',
      'select_street': 'Chagua Mtaa/Kijiji',
      'select_place': 'Chagua Kitongoji',
      'update_property': 'Sasisha Jengo',
      'confirm_vacate': 'Thibitisha Kusitisha',
      'vacate_message':
          'Je, una uhakika unataka kusitisha mkataba na kuifanya nyumba hii kuwa wazi?',
      'vacate_success': 'Mpangaji ameondolewa kikamilifu',
      'vacate_failed': 'Imeshindikana kuondoa mpangaji',
      'vacate_house': 'Ondoa Mpangaji',
      'confirm_delete': 'Je, una uhakika unataka kufuta',
    },
  };

  String translate(String key) {
    final String languageCode = LocalizationService.instance.currentLanguage;
    String v = _localizedValues[languageCode]?[key] ?? '';
    if (v.isEmpty) v = key;
    // Prettify keys that look like snake_case or fallback keys
    if (v.contains('_')) {
      v = v.replaceAll('_', ' ');
      if (v.isNotEmpty) {
        v = v[0].toUpperCase() + v.substring(1);
      }
    }
    return v;
  }
}
